### ISSUE TITLE
The `elements` attribute is required for the RDKitConverter but is not present in this AtomGroup. Please refer to the documentation to guess elements from other attributes or type `help(MDAnalysis.topology.guessers)`

### ISSUE THREAD

**Issue by vvithurshan** [chemosim-lab/ProLIF#101]
getting an error while executing the following code
fp = plf.Fingerprint()
fp.run(u.trajectory[::10], lig, prot)
df = fp.to_dataframe(return_atoms=True)

The `elements` attribute is required for the RDKitConverter but is not present in this AtomGroup. Please refer to the documentation to guess elements from other attributes or type `help(MDAnalysis.topology.guessers)`

**Comment by cbouy** [comment]
Hi,

Have you tried typing the command shown in the error message?
`help(mda.topology.guessers)`
In your case the solution probably looks something like inserting the
following piece of code before generating the fingerprint:
```python
elements = [
    mda.topology.guessers.guess_atom_element(x)
    for x in u.atoms.names
]
u.add_TopologyAttr("elements", elements)
```

Le mer. 23 nov. 2022 à 06:15, V _VITHURSHAN ***@***.***> a
écrit :

**Comment by vvithurshan** [comment]
> Hi, Have you tried typing the command shown in the error message? `help(mda.topology.guessers)` In your case the solution probably looks something like inserting the following piece of code before generating the fingerprint: ```python elements = [ mda.topology.guessers.guess_atom_element(x) for x in u.atoms.names ] u.add_TopologyAttr("elements", elements) ```

Thank you, it worked
