### ISSUE TITLE
Example for processing docked structures

### ISSUE THREAD

**Issue by PatWalters** [chemosim-lab/ProLIF#11]
Your examples seem to be oriented toward processing trajectories, which is great, but I'm unclear on how to generate interaction fingerprints from a set of docked structures.  Would it be possible to provide an example where you generate interaction fingerprints from a protein in a PDB file and a set of ligands in an SDF. 

Thanks!

**Comment by cbouy** [comment]
Hi @PatWalters, thank you for the suggestion!
Here's a code snippet on how to achieve that:

```python
import prolif as plf
from rdkit import Chem

def sdf_supplier(sdf_file):
    suppl = Chem.SDMolSupplier(sdf_file)
    for mol in suppl:
        # to work properly prolif needs a residue name and number for every atom
        for atom in mol.GetAtoms():
            mi = Chem.AtomPDBResidueInfo(atom.GetSymbol(), residueName="UNK", residueNumber=1)
            atom.SetMonomerInfo(mi)
        yield plf.Molecule(mol)

def run_fp(lig, prot, frame=0):
    """Equivalent to what happens in the fp.run method but using directly
    a plf.Molecule instead of an MDAnalysis atomgroup"""
    data = {"Frame": frame}
    for lres in lig:
        for presid in plf.get_residues_near_ligand(lres, prot):
            bv = fp.bitvector(lres, prot[presid])
            data[(lres.resid, presid)] = bv
    return data

ifp = []
fp = plf.Fingerprint()
prot = mda.Universe(PDB_FILEPATH)
prot = plf.Molecule.from_mda(prot)
lig_suppl = sdf_supplier(SDF_FILEPATH)
for i, lig in enumerate(lig_suppl):
    data = run_fp(lig, prot, frame=i)
    ifp.append(data)

df = plf.to_dataframe(ifp, fp.interactions.keys())
```

I'll add this example to the documentation later on. I'll also add the sdf_supplier and run_fp functions directly in the package so that it's more easily usable instead of copy-pasting code from the documentation.
I'll close the issue when that's done, but don't hesitate if you have other questions.

**Comment by cbouy** [comment]
@PatWalters I've integrated the above changes in ProLIF v0.3.1
You can check the updated example code [here](https://prolif.readthedocs.io/en/latest/notebooks/how-to.html#Working-with-docking-poses-instead-of-MD-simulations).
Feel free to reopen if you have other question related to processing docking poses!
