### ISSUE TITLE
fp.run error when try docking pose with PDBQT File

### ISSUE THREAD

**Issue by anpham2209** [chemosim-lab/ProLIF#111]
Hello,
I am trying to get the IFP from AutoDock Vina’s output with pdbqt file as instruction in readthedoc, but when i run the fp.run_from_iterable(lig_suppl, prot) it get error
Here is the code:
LOAD LIGAND
`pdbqt_files = '/home/labhhc/Downloads/AN_ProLIF/active_1.pdbqt'` - this is the result after i run vina_split
`template = Chem.MolFromPDBFile("/home/labhhc/Downloads/AN_ProLIF/active_1.pdb")` - i use pdb instead of smiles but i guess it's not a problem
`u= mda.Universe('/home/labhhc/Downloads/AN_ProLIF/4o2b_protein_fixed.pdb')`  - i input the protein that i use to dock        
`prot = u.select_atoms("protein")`

`lig_suppl = plf.pdbqt_supplier(pdbqt_files, template)`
`fp = plf.Fingerprint()`
`fp.run_from_iterable(lig_suppl, prot)`
`df = fp.to_dataframe()`
`df`

**RETURN**
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[107], line 3
      1 lig_suppl = plf.pdbqt_supplier(pdbqt_files, template)
      2 fp = plf.Fingerprint()
**----> 3 fp.run_from_iterable(lig_suppl, prot)**
      4 df = fp.to_dataframe()
      5 df

File ~/anaconda3/envs/ProLIF/lib/python3.8/site-packages/prolif/fingerprint.py:593, in Fingerprint.run_from_iterable(self, lig_iterable, prot_mol, residues, progress, n_jobs)
    591     raise ValueError("n_jobs must be > 0 or None")
    592 if n_jobs != 1:
**--> 593     return self._run_iter_parallel(**
    594         lig_iterable=lig_iterable,
    595         prot_mol=prot_mol,
    596         residues=residues,
    597         progress=progress,
    598         n_jobs=n_jobs,
    599     )
    601 iterator = tqdm(lig_iterable) if progress else lig_iterable
    602 if residues == "all":

File ~/anaconda3/envs/ProLIF/lib/python3.8/site-packages/prolif/fingerprint.py:634, in Fingerprint._run_iter_parallel(self, lig_iterable, prot_mol, residues, progress, n_jobs)
    628 with mp.Pool(
    629     n_jobs,
    630     initializer=declare_shared_objs_for_mol,
    631     initargs=(self, prot_mol, residues),
    632 ) as pool:
    633     results = []
**--> 634     for data in tqdm(**
    635         pool.imap_unordered(process_mol, suppl),
    636         total=total,
    637         disable=not progress,
    638     ):
    639         results.append(data)
    640 results.sort(key=lambda ifp: ifp["Frame"])

File ~/anaconda3/envs/ProLIF/lib/python3.8/site-packages/tqdm/notebook.py:259, in tqdm_notebook.__iter__(self)
    257 try:
    258     it = super(tqdm_notebook, self).__iter__()
**--> 259     for obj in it:**
    260         # return super(tqdm...) will not catch exception
    261         yield obj
    262 # NB: except ... [ as ...] breaks IPython async KeyboardInterrupt

File ~/anaconda3/envs/ProLIF/lib/python3.8/site-packages/tqdm/std.py:1195, in tqdm.__iter__(self)
   1192 time = self._time
   1194 try:
**-> 1195     for obj in iterable:**
   1196         yield obj
   1197         # Update and possibly print the progressbar.
   1198         # Note: does not call self.update(1) for speed optimisation.

File ~/anaconda3/envs/ProLIF/lib/python3.8/multiprocessing/pool.py:868, in IMapIterator.next(self, timeout)
    866 if success:
    867     return value
**--> 868 raise value**

**ValueError**: '' isn't a valid topology format, nor a coordinate format
   from which a topology can be minimally inferred.
   You can use 'Universe(topology, ..., topology_format=FORMAT)'
   to explicitly specify the format and
   override automatic detection. Known FORMATs are:
   dict_keys(['PSF', 'TOP', 'PRMTOP', 'PARM7', 'PDB', 'ENT', 'XPDB', 'PQR', 'GRO', 'CRD', 'PDBQT', 'DMS', 'TPR', 'MOL2', 'DATA', 'LAMMPSDUMP', 'XYZ', 'TXYZ', 'ARC', 'GMS', 'CONFIG', 'HISTORY', 'XML', 'MMTF', 'GSD', 'MINIMAL', 'ITP', 'IN', 'FHIAIMS', 'PARMED', 'RDKIT', 'OPENMMTOPOLOGY', 'OPENMMAPP'])
   See https://docs.mdanalysis.org/documentation_pages/topology/init.html#supported-topology-formats
   For missing formats, raise an issue at 
   https://github.com/MDAnalysis/mdanalysis/issues

Thank you very much for your help
Regards,
An.

**Comment by rwxayheee** [comment]
Hi, 
The protein for run_from_iterable needs to be a prolif.molecule.Molecule. 
`prot = u.select_atoms("protein")`
returns AtomGroups. 
Will that work for you if you create prot by the following:
`prot = prolif.Molecule.from_mda(u, "protein")`

**Comment by anpham2209** [comment]
> Hi, The protein for run_from_iterable needs to be a prolif.molecule.Molecule. `prot = u.select_atoms("protein")` returns AtomGroups. Will that work for you if you create prot by the following: `prot = prolif.Molecule.from_mda(u, "protein")`

Thanks for your help, the prot have change to type as prolif.molecule.Molecule but the error still the same :(

**Comment by cbouy** [comment]
Hi An,

As @rwxayheee said (thanks for the help!) you'll need a `prolif.Molecule` object for the protein when you use `fp.run_from_iterable`, so you can either do:
```python
prot = u.select_atoms("protein")
prot = prolif.Molecule.from_mda(prot)
```
or directly
```python
prot = prolif.Molecule.from_mda(u, "protein")
```

However you'll run into another problem in your case: **for the template molecule you cannot use a PDB**. The aim of this template molecule is to provide the bond orders and charges (which the PDBQT file does not contain) to build a complete molecule (bond, orders, formal charges, and coordinates). So you'll need a **SMILES, MOL2 or SDF** for that.  
If you don't, you might still be able to use your PDB file, but **only if it contains all hydrogen atoms explicitly**, in which case you can use:
```python
lig_pdb = mda.Universe("/home/labhhc/Downloads/AN_ProLIF/active_1.pdb")
template = prolif.Molecule.from_mda(lig_pdb)
```

Once both problems are fixed you should be able to use `fp.run_from_iterable(lig_suppl, prot)` successfully.

**Comment by cbouy** [comment]
Oh and I forgot: `pdbqt_files ` needs to be a list!

**Comment by anpham2209** [comment]
> Oh and I forgot: `pdbqt_files ` needs to be a list!

Thank you so much, now the error has change i have update my code like this:

`pdbqt_files = sorted(glob.glob('/home/labhhc/Downloads/AN_ProLIF/active_1_*.pdbqt'))`  --list of pdbqt file
`lig_pdb = mda.Universe("/home/labhhc/Downloads/AN_ProLIF/active_1.pdb")'` - i have check by py3D mol that ligand contain Hydrogen @@
`template = plf.Molecule.from_mda(lig_pdb)`
`u= mda.Universe('/home/labhhc/Downloads/AN_ProLIF/4o2b_protein_fixed.pdb') `
`prot = plf.Molecule.from_mda(u,'protein')`

`lig_suppl = plf.pdbqt_supplier(pdbqt_files, template)`
`fp = plf.Fingerprint()`
`fp.run_from_iterable(lig_suppl, prot)`

**RETURN**

ValueError                                Traceback (most recent call last)
Cell In[20], line 3
      1 lig_suppl = plf.pdbqt_supplier(pdbqt_files, template)
      2 fp = plf.Fingerprint()
**----> 3 fp.run_from_iterable(lig_suppl, prot)**
      4 df = fp.to_dataframe()
      5 df

File ~/anaconda3/envs/ProLIF/lib/python3.8/site-packages/prolif/fingerprint.py:593, in Fingerprint.run_from_iterable(self, lig_iterable, prot_mol, residues, progress, n_jobs)
    591     raise ValueError("n_jobs must be > 0 or None")
    592 if n_jobs != 1:
**--> 593     return self._run_iter_parallel(**
    594         lig_iterable=lig_iterable,
    595         prot_mol=prot_mol,
    596         residues=residues,
    597         progress=progress,
    598         n_jobs=n_jobs,
    599     )
    601 iterator = tqdm(lig_iterable) if progress else lig_iterable
    602 if residues == "all":

File ~/anaconda3/envs/ProLIF/lib/python3.8/site-packages/prolif/fingerprint.py:634, in Fingerprint._run_iter_parallel(self, lig_iterable, prot_mol, residues, progress, n_jobs)
    628 with mp.Pool(
    629     n_jobs,
    630     initializer=declare_shared_objs_for_mol,
    631     initargs=(self, prot_mol, residues),
    632 ) as pool:
    633     results = []
**--> 634     for data in tqdm(**
    635         pool.imap_unordered(process_mol, suppl),
    636         total=total,
    637         disable=not progress,
    638     ):
    639         results.append(data)
    640 results.sort(key=lambda ifp: ifp["Frame"])

File ~/anaconda3/envs/ProLIF/lib/python3.8/site-packages/tqdm/notebook.py:259, in tqdm_notebook.__iter__(self)
    257 try:
    258     it = super(tqdm_notebook, self).__iter__()
**--> 259     for obj in it:**
    260         # return super(tqdm...) will not catch exception
    261         yield obj
    262 # NB: except ... [ as ...] breaks IPython async KeyboardInterrupt

File ~/anaconda3/envs/ProLIF/lib/python3.8/site-packages/tqdm/std.py:1195, in tqdm.__iter__(self)
   1192 time = self._time
   1194 try:
**-> 1195     for obj in iterable:**
   1196         yield obj
   1197         # Update and possibly print the progressbar.
   1198         # Note: does not call self.update(1) for speed optimisation.

File ~/anaconda3/envs/ProLIF/lib/python3.8/multiprocessing/pool.py:868, in IMapIterator.next(self, timeout)
    866 if success:
    867     return value
**--> 868 raise value**

**ValueError: No matching found**

Thank you very much for your help
Regards,
An.

**Comment by cbouy** [comment]
Ah right, the template shouldn't contain hydrogen atoms, so right after `template = prolif.Molecule.from_mda(lig_pdb)`, you can add `template = Chem.RemoveAllHs(template)` and it should (hopefully) work this time!

```python
pdbqt_files = sorted(glob.glob('/home/labhhc/Downloads/AN_ProLIF/active_*.pdbqt'))
lig_pdb = mda.Universe("/home/labhhc/Downloads/AN_ProLIF/active_1.pdb")
template = plf.Molecule.from_mda(lig_pdb)
template = Chem.RemoveAllHs(template)
# optional: check that PDBQT files work correctly or fail early
list(plf.pdbqt_supplier([pdbqt_files[0]], template))

u = mda.Universe('/home/labhhc/Downloads/AN_ProLIF/4o2b_protein_fixed.pdb') 
prot = plf.Molecule.from_mda(u,'protein')
lig_suppl = plf.pdbqt_supplier(pdbqt_files, template)

fp = plf.Fingerprint()
fp.run_from_iterable(lig_suppl, prot)

```

**Comment by anpham2209** [comment]
It's work this time. Thank you very much <3 
One more question, I want to visualize interaction between the ligand docking pose result with the protein. So, According to instruction I using LigPlot as below:
`lig_suppl = plf.pdbqt_supplier(pdbqt_files, template)`
`fp = plf.Fingerprint()`
`fp.run_from_iterable(lig_suppl, prot)`
`df = fp.to_dataframe(return_atoms=True)`
`df`
Return: 

ligand | UNL1


protein | ALA180.A | ALA314.B | ASN256.B


interaction | VdWContact | VdWContact | VdWContact
-- | -- | -- | --



-- | -- | -- | --





Frame 0 (None, None) | (None, None) | (None, None)
Frame 1 (21, 0) | (16, 0) | (22, 0)

`df = fp.to_dataframe(return_atoms=True)`
`net = LigNetwork.from_ifp(`
`    df,`
`    template,`
`    # replace with `kind="frame", frame=0` for the other depiction`
`    kind="frame",`
`    threshold=0,`
`    rotation=540,`
`)`
`net.display()`
 Return: I only see the structure of my ligand with no amino acid interaction like VdWContact. How to fix that please
Best Regard,
An

**Comment by anpham2209** [comment]
Opps, turn out that is because i change kind to "frame" instead of "agrregate". Thank you so much again, i will close this comment
