### ISSUE TITLE
fp.to_dataframe(return_atoms=True,drop_empty=True) still slow

### ISSUE THREAD

**Issue by ReneHamburger1993** [chemosim-lab/ProLIF#112]
Hi,

I have 25k frames that I analyzed and it took ~5min to get the full atomid DataFrame with my selections.

I traced it down to the grouping including the "empty" columns.

If we remove them before grouping it gets much faster.

1000 frames: 10s -> ~2s
25k frames: ~300s -> 60s

Though its a factor of 5 faster now.
I will open a PR with my optimization.

Kind regards
René

**Comment by cbouy** [comment]
Hi René and thanks a lot for reporting this and contributing, I'll try to have a look at your PR this week.

Best,
Cédric
