### ISSUE TITLE
Hints to use the visualization section of the documentation in the case of "Working with docking poses instead of MD simulations"

### ISSUE THREAD

**Issue by xavgit** [chemosim-lab/ProLIF#115]
Hi,
thanks for your work.
I have a request for the documentation.
It is possible to get hints about how to modify  the Python code of the visualization section in the case of
 "Working with docking poses instead of MD simulations"?
In this case I have a the pdb file of the receptor and the sdf file of the vina output instead of the results of an Md simulation.

Thanks.
Saverio

**Comment by cbouy** [comment]
Hi @xavgit,

Sure, I plan to do an overhaul of the docs at some point, and having the information split across multiple pages and mostly focused on MD isn't ideal.
In the meantime, assuming you've run the analysis with a PDB receptor and SDF ligand you should already have a code snippet that looks like this:

```python
# load protein
prot = mda.Universe(plf.datafiles.datapath / "vina" / "rec.pdb")
pmol = plf.Molecule.from_mda(prot)

# load ligands
path = str(plf.datafiles.datapath / "vina" / "vina_output.sdf")
lig_suppl = plf.sdf_supplier(path)

# generate fingerprint
fp = plf.Fingerprint()
fp.run_from_iterable(lig_suppl, prot)
df = fp.to_dataframe()
```

In the visualization section, the most important objects are going to be:

- `pmol` which is a `prolif.Molecule` object containing your protein and the residues as separate sub-molecules. You already have this in the snippet above.
- `lmol`, this one corresponds to a `prolif.Molecule` object of your ligand/docking pose. You can obtain it with `lmol = lig_suppl[0]`, just replace `0` with the index of the docking pose you want to visualize.
- a pandas DataFrame `df` containing the indices of atoms performing the interaction. You can get it with `fp.to_dataframe(return_atoms=True)`

With this you should be able to run any visualization script.
If this works for you, please close the issue.

Best,
Cédric
