### ISSUE TITLE
Docked structure in SMINA problems

### ISSUE THREAD

**Issue by syedzayyan** [chemosim-lab/ProLIF#134]
Hello!

I have docked a few molecules with SMINA and have sdf files as output. I am now trying to generate fingerprints from this however for most molecules, I have this kind of error:

```
09:44:49] Explicit valence for atom # 9 N, 4, is greater than permitted
[09:44:49] ERROR: Could not sanitize molecule ending on line 55
[09:44:49] ERROR: Explicit valence for atom # 9 N, 4, is greater than permitted
```

I was wondering why that is the case. SMINA could dock them I do have affinity values, why is there a fingerprint issue? Is it because the docked structures are invalid?

Apologies for the extremely noob question.

**Comment by rwxayheee** [comment]
Hi @syedzayyan! This looks like an error message from the RDKit components of ProLIF. One thing you could check is the charge specification of the questioned N. See http://c4.cabrillo.edu/404/ctfile.pdf pg. 13, Field "ccc" for charge specification in the atom block of sdf files. 
Normally, RDKit is able to handle N+ if charge = +1 is properly specified. Depending on how the sdf files are generated, the information might have been lost.

**Comment by syedzayyan** [comment]
Hello!

I re-docked my ligands to generate pdbqt files in Smina. I encounter the same error. I was wondering if it was a file problem too but even with the pdbqt supplier and templates with SMILES I encounter the same problem.

"CN1CCN(C2=Nc3ccccc3Nc3sc(CO)cc32)CC1" <-- This is one of the smiles that keep failing. 

Is it that a bunch of smiles on ChEMBL have the same problem? Pardon my ignorance here, I am not a chemist.

Thanks for the help so far!

**Comment by cbouy** [comment]
So this is the content of your PDBQT file and the template that you're trying to match:
![image](https://github.com/chemosim-lab/ProLIF/assets/27850535/771eb63f-672c-4cb3-a30f-93a180cdda6a)

There are 3 atoms in there (circled in orange) that have hydrogen atoms added for some reason, which makes it impossible to match your template while preserving the formal charges and bond orders specified in the template:
![image](https://github.com/chemosim-lab/ProLIF/assets/27850535/d847a3fc-c841-42a5-83b6-288000e56919)

I'm guessing this is an issue with the ligand preparation in Smina?

Here's a code snippet if you want to generate the comparison image above for other ligands that fail:
```python
import MDAnalysis as mda
from rdkit import Chem
from rdkit.Chem import rdDepictor, rdFMCS, AllChem, Draw

rdDepictor.SetPreferCoordGen(True)

def display_pdbqt_and_template(pdbqt_path, template_smiles):
    template = Chem.MolFromSmiles(template_smiles)
    pdbqt = mda.Universe(pdbqt_path)
    elements = [
        mda.topology.guessers.guess_atom_element(x) for x in pdbqt.atoms.names
    ]
    pdbqt.add_TopologyAttr("elements", elements)
    pdbqt.add_TopologyAttr("chainIDs", pdbqt.atoms.segids)
    pdbqt.atoms.types = pdbqt.atoms.elements
    pdbqt_mol = pdbqt.atoms.convert_to.rdkit(NoImplicit=False)
    mcs = rdFMCS.FindMCS([pdbqt_mol, template], bondCompare=rdFMCS.BondCompare.CompareAny)
    AllChem.Compute2DCoords(template)
    AllChem.GenerateDepictionMatching2DStructure(pdbqt_mol, template, refPatt=mcs.queryMol)
    return Draw.MolsToGridImage(
        [template, pdbqt_mol], legends=["template", "PDBQT"], subImgSize=(300, 300)
    )

display_pdbqt_and_template("CHEMBL100454_pose_1.pdbqt", "CN1CCN(C2=Nc3ccccc3Nc3sc(CO)cc32)CC1")
```

Hope this clarifies things a bit!
And thanks @rwxayheee for the help!

**Comment by rwxayheee** [comment]
Hi @cbouy, thanks so much with your kind reply as always! @syedzayyan, I suggest to look at the input file you used for ligand preparation, or the source pdbqt file you used for the docking. 

From your output pdbqt, I see that both carbons (highlighted in the above figures) are typed as "A" (aromatic carbon). AutoDock seems aware that these are aromatic carbons. 

My guess is, your initial ligand structure file is a +2 protomer of this ligand. But the formal charge and bond information is lost in the (old-style) pdbqt files. Without this information, RDKit will assume no formal charge and therefore place implicit hydrogens at those positions.

**Comment by syedzayyan** [comment]
Thank you @rwxayheee  and @cbouy for the comments. It was a problem with the compound generation phase, I think. I don't know how it occured but it did. For anyone interested in the future with more programming and cheminformatics experience and not a copypaster like me, [this is the tutorial ](https://projects.volkamerlab.org/teachopencadd/talktorials/T015_protein_ligand_docking.html)I was following.

I ended up using meeko and then Autodock Vina Python bindings and it works!
