### ISSUE TITLE
Plotting ligand interaction network from molecular docking results.

### ISSUE THREAD

**Issue by Sumbul1631** [chemosim-lab/ProLIF#137]
I am trying to plot ligand interaction network from docking results , I have used the code that have been provided in discussions section....My code looks like this:
!pip install rdkit
!pip install prolif
from rdkit import Chem
import prolif as plf
from prolif.plotting.network import LigNetwork

# Load ligand
lig_suppl = plf.sdf_supplier("/content/d2 top.sdf")

# Load protein
prot_pdb = Chem.MolFromPDBFile("/content/final prepared structure of protein.pdb", removeHs=False)
prot = plf.Molecule(prot_pdb)

# Run prolif
fp = plf.Fingerprint()
fp.run_from_iterable(lig_suppl, prot)
df = fp.to_dataframe()
print(df)

# Visualize
df_atoms = fp.to_dataframe(return_atoms=True)
net = LigNetwork.from_ifp(df_atoms, lig_suppl[0], kind="frame", frame=0)
net.show("pdb_lig_network.html")

Plifs get displayed but not the interaction network  and it says....localhost refused o connect

**Comment by cbouy** [comment]
Hi @Sumbul1631, how are you running this code snippet: Google colab, Jupyter notebook, python script?

**Comment by Sumbul1631** [comment]
Google colab

**Comment by cbouy** [comment]
Looks like Colab doesn't make it easy to display an HTML file saved locally looking at this [stackoverflow thread](https://stackoverflow.com/questions/59091645/serving-an-iframe-in-google-colab-notebook-localhost-refused-to-connect).

Can you try replacing the last line `net.show("pdb_lig_network.html")` with `net.display()` ? If you need to save the html file you can still just do `net.save("/path/to/output.html")` before/after.

**Comment by Sumbul1631** [comment]
Yes..I tried it and it worked..thank you
