### ISSUE TITLE
Problem with computing PLIFS from docking results

### ISSUE THREAD

**Issue by Sumbul1631** [chemosim-lab/ProLIF#140]
I am computing PLIFS from docking results.....When i use the following code to read my protein, It gives me only hydrophobic interactions:
prot = mda.Universe(plf.datafiles.datapath / "vina" / "rec.pdb")
prot = plf.Molecule.from_mda(prot)
Instead when i read my protein using the following code, it gives me all types of interactions.. So can I use this instead of reading my molecule with mda unverse object?
prot_pdb = Chem.MolFromPDBFile("/content/5ht2a prepared structure-use.pdb", removeHs=False)
prot = plf.Molecule(prot_pdb)

**Comment by cbouy** [comment]
You need to replace `plf.datafiles.datapath / "vina" / "rec.pdb"` with the actual path to your PDB file so something like

```python
u = mda.Universe("/content/5ht2a prepared structure-use.pdb")
prot = plf.Molecule.from_mda(u)
```

Using `Chem.MolFromPDBFile` will work if you only have "standard" residues in your protein, but for things like charged histidines I don't know if RDKit handles them correctly (i.e. if it keeps the charge at the correct location or not)

Please close the issue if this answers your question,
Best,
Cédric
