### ISSUE TITLE
Barcode visualization

### ISSUE THREAD

**Issue by AhmedHassanin-IPB** [chemosim-lab/ProLIF#151]
I have got an error with the barcode generated png, it did not contain any label.,
I used the '**fp.plot_barcode()**' without any arguments but it shows me that error.
"Axis.set_ticks() take 2 positional arguments but 3 were given" 
![barcode](https://github.com/chemosim-lab/ProLIF/assets/117353932/074357f9-656f-4ab2-9f66-ca19b74722a1)

**Comment by cbouy** [comment]
Which version of matplotlib are you using? 
3.7 should work (and 3.6 as well if I remember correctly), I haven't tried older versions so could be that

**Comment by AhmedHassanin-IPB** [comment]
Thanks so much, it was an old version of matplotlib (3.4), I have updated, and works fine ..
