### ISSUE TITLE
Interaction fingerprint show only VdW interaction

### ISSUE THREAD

**Issue by Le-Phung-Hien** [chemosim-lab/ProLIF#157]
Hi, 

I have run a modified script to plot interaction between 
[protein.pdb.txt](https://github.com/chemosim-lab/ProLIF/files/12591646/protein.pdb.txt) and [ligands.sdf.txt](https://github.com/chemosim-lab/ProLIF/files/12591648/ligands.sdf.txt). However, the interaction fingerprint show only VdW interaction:
![Figure_1](https://github.com/chemosim-lab/ProLIF/assets/114122870/0d8633df-100f-440e-a997-9bb332d8ca7f)
Many ligands have charged nitrogen so I expected that there should be some hydrogen bonds or salt bridges. 
When I open the first ligand on Maestro and quite a bit is going on:
![Maestro](https://github.com/chemosim-lab/ProLIF/assets/114122870/9e197f23-d6e3-474b-85b3-5ba6ea285ff4)
Please tell me if there is something wrong with my files or something.

Thanks!

```
import MDAnalysis as mda
import prolif as plf
import sys
import argparse
import os
from IPython.display import display
from matplotlib import pyplot as plt

# Create an argument parser
parser = argparse.ArgumentParser(description='Protein-ligand interaction barcoding')

# Add arguments
parser.add_argument('-p', '--protein', type=str, help='Path to the protein file')
parser.add_argument('-l', '--ligands', type=str, help='Path to the ligand file')

# Parse the command-line arguments
args = parser.parse_args()

protein = args.protein
ligands = args.ligands

# Read the protein file
u = mda.Universe(protein)
protein_mol = plf.Molecule.from_mda(u)

# Load ligands
poses_path = str(os.path.abspath(ligands))
if ligands.endswith('.sdf'):
    pose_iterable = plf.sdf_supplier(poses_path)
if ligands.endswith('.mol2'):
    pose_iterable = plf.mol2_supplier(poses_path)
    
# Use default interactions
fp = plf.Fingerprint()

# Run on your poses
fp.run_from_iterable(pose_iterable, protein_mol)

# show dataframe
df = fp.to_dataframe(index_col="Compound")
display(df)

# show barcode
fp.plot_barcode(xlabel="Pose")
plt.show()

# show first compound's interactions
fp.plot_lignetwork(pose_iterable[0])
```

**Comment by Le-Phung-Hien** [comment]
FYI, I installed the dependencies via conda and prolif via pip, this is the list of package currently in by environment: [package_list.txt](https://github.com/chemosim-lab/ProLIF/files/12591695/package_list.txt).

**Comment by rwxayheee** [comment]
Hi @Le-Phung-Hien, 
I'm not very sure what's not working with 

> u = mda.Universe(protein)

but parsing the protein PDB with RDKit seemed to work.. (although this is not the first choice to set up the receptor especially with nonstandard residue names, read more at: https://prolif.readthedocs.io/en/stable/notebooks/pdb.html#pdb)

`python
import MDAnalysis as mda
import prolif as plf
from rdkit import Chem

rdkit_prot = Chem.MolFromPDBFile("protein.pdb", removeHs=False)
rdkit_protein_mol = plf.Molecule(rdkit_prot)

fp = plf.Fingerprint()
pose_iterable = plf.sdf_supplier("ligands.sdf")
fp.run_from_iterable(pose_iterable, rdkit_protein_mol)
df = fp.to_dataframe()
df.to_csv("myfp.csv")`
[myfp.csv](https://github.com/chemosim-lab/ProLIF/files/12592288/myfp.csv)

@cbouy, thanks again for this great work and your kind advice as always.

**Comment by rwxayheee** [comment]
Hi @Le-Phung-Hien! Yes, I think the topology of the original PDB file was not corrected perceived by MDAalysis. But I don't know which exact topology attributes were incomplete (bonds? atom types?). Maybe @cbouy could help us with this.. 

Just FYI, there's another solution, if you are ok with some minimal editing on your PDB file: just remove all CONECT lines. Then, when you run: 
````python
# Read the protein file
u = mda.Universe(protein)
protein_mol = plf.Molecule.from_mda(u)
````
A warning message will appear saying that MDA is gonna guess the bonds because no CONECT information is found in the input pdb file:

> /Users/he.1768/anaconda3/envs/prolif/lib/python3.11/site-packages/MDAnalysis/converters/RDKit.py:472: UserWarning: No `bonds` attribute in this AtomGroup. Guessing bonds based on atoms coordinates

With that, the interaction fingerprints will show all types of interactions as expected :)

**Comment by cbouy** [comment]
@rwxayheee you've pretty much found the problem at that point: there's a CONECT records in the PDB file, so MDAnalysis assumes that all bonds are present and won't do the bond guessing for the rest unless you force it to by specifying `guess_bonds=True` when creating the `Universe` object. This is stated in the [Prerequisite section](https://prolif.readthedocs.io/en/stable/notebooks/pdb.html#prerequisite) of the tutorial for PDB files 😅 

> Important
> Make sure that each file produced either has all bonds explicitely stated, or none of them.

Thank you for the help again 🙌
