### ISSUE TITLE
Intramolecular Pi-hbond between the N-H of a peptide bond and residues with pi systems

### ISSUE THREAD

**Issue by DipBobDar** [chemosim-lab/ProLIF#159]
Thanks for your suggestion.

I wanted to check intramolecular interaction in a peptide and was initerested in the hbond-pi interactions between N-H in the peptide bond and pi-system residues like Tyr, Phe, Trp. Is it possible to use the existing format to do this or I need to do something else.

Thanks in advance.

_Originally posted by @DipBobDar in https://github.com/chemosim-lab/ProLIF/issues/158#issuecomment-1722850131_

**Comment by cbouy** [comment]
Ah yes then it's the opposite of what I had assumed in the previous thread. That would be:

```python
class BackboneNHPi(plf.interactions.CationPi):
    def __init__(self):
        super().__init__(cation="[$([N;+0](-[H])-[C;X4]-[C^2]=O)]")

fp = plf.Fingerprint(interactions=["BackboneNHPi"])
```

And then you can use this `fp` fingerprint object for the analysis as shown in the tutorials.

Please close the issue if that answers your question

**Comment by DipBobDar** [comment]
Thanks a lot. That helps.
