### ISSUE TITLE
Error import prolif 

### ISSUE THREAD

**Issue by groponp** [chemosim-lab/ProLIF#162]
I'm try test if prolif are right install then get this error after do "import prolif"

raceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/macbookpro/Downloads/prolif.py", line 5, in <module>
    u = mda.Universe(plf.datafiles.TOP, plf.datafiles.TRAJ)
AttributeError: partially initialized module 'prolif' has no attribute 'datafiles' (most likely due to a circular import)

**Comment by cbouy** [comment]
Hi,

You have to name your Python script something else than the name of the package that you import (this stands for any package, not just prolif)

**Comment by groponp** [comment]
ok, It work for me.  Thanks so much.
