### ISSUE TITLE
TypeError: 'float' object is not subscriptable

### ISSUE THREAD

**Issue by pineappleK** [chemosim-lab/ProLIF#17]
Greetings.

Here are the codes:

``` python
prot1 = u.atoms.select_atoms("resid 11")
prot2 = u.atoms.select_atoms("protein")

fp = plf.Fingerprint(['HBDonor', 'HBAcceptor', 'PiStacking', 'Anionic', 'Cationic', 'CationPi', 'PiCation'])
fp.run(u.trajectory[:2], prot1, prot2)
print(fp.ifp)
df = fp.to_dataframe(dtype=np.uint8)
print(df)
 ```
``` diff
+ The outputs look good:
```

![image](https://user-images.githubusercontent.com/45991911/113295973-77570300-932b-11eb-9fe5-4703db08f408.png)

However, if I just **change `fp.run(u.trajectory[:2], prot1, prot2)` to `fp.run(u.trajectory[:3], prot1, prot2)`**, 
``` diff
- the programm will raise an error::
```

![image](https://user-images.githubusercontent.com/45991911/113296185-b8e7ae00-932b-11eb-894b-ee5983303d21.png)

Thanks for your attention.

pineapple

**Comment by cbouy** [comment]
Hi @pineappleK 

Can you tell me which version of ProLIF are you using ?
Try running `print(plf.__version__)` from Python, and if it says `0+unknown`, then run `pip list | grep prolif` in a terminal

Thank you,

Cedric

**Comment by pineappleK** [comment]
![image](https://user-images.githubusercontent.com/45991911/113324992-5ce05200-934a-11eb-8a39-d0271ec8f789.png)
![image](https://user-images.githubusercontent.com/45991911/113325034-6f5a8b80-934a-11eb-8bd5-df29ec9cf1fa.png)

Thank you, 
pineapple

**Comment by cbouy** [comment]
I've made some changes in v0.3.1 regarding the `fp.to_dataframe` method which likely fixed this.
Can you reinstall prolif to the latest version ?
```
pip uninstall -y prolif
pip install git+https://github.com/chemosim-lab/ProLIF.git
```
Hopefully that will fix the issue

Thanks,
Cedric

**Comment by pineappleK** [comment]
The reason that I chose v0.3.0 is that the installation of v0.3.1 met some **errors**.
I have tried 
``` shell
pip install git+https://github.com/chemosim-lab/ProLIF.git
pip install https://github.com/chemosim-lab/ProLIF/archive/v0.3.1.zip
```
![image](https://user-images.githubusercontent.com/45991911/113412976-3bd03d80-93ec-11eb-8ff4-4216c00d1904.png)

**Comment by cbouy** [comment]
Mmh it's strange I just reinstalled it without any problem on my side.

Are you installing in a clean conda environment ?
What version of python and pip are you using ?
Also, can you try this:
```
pip install -U pip setuptools
conda update -c conda-forge ca-certificates
```
And then uninstall prolif and reinstall ?

Thanks,
Cedric

**Comment by pineappleK** [comment]
!! **Thanks, it works.**

I want to ask you another question.

since my trajectory contains 150000 frames, it will be very very very  **slow** to perform `fp.run()`, which will take about 24 hours.

Is there any method that I can use to parallelly perform `fp.run()` ? For example, `concurrent.futures.ThreadPoolExecutor`?

Thanks, 
pineapple

**Comment by cbouy** [comment]
Haven't tried but you could try something like this:

```python
import multiprocessing as mp
from tqdm.auto import tqdm
import prolif as plf
import MDAnalysis as mda

# setup the mda.Universe, lig and prot
# ...

N_PROCESSES = 8
n_frames = 150000
interactions = ['HBDonor', 'HBAcceptor', 'PiStacking', 'Anionic', 'Cationic', 'CationPi', 'PiCation']

def job(i):
    fp = plf.Fingerprint(interactions)
    fp.run(u.trajectory[i], lig, prot, progress=False)
    return fp.ifp[0]

with mp.Pool(N_PROCESSES) as pool:
    results = []
    for ifp in tqdm(pool.imap_unordered(job, range(n_frames)),
                    total=n_frames):
        results.append(ifp)

df = plf.to_dataframe(results, interactions, dtype=np.uint8)
```

**Comment by pineappleK** [comment]
:) Thanks, it works but with a little error.

``` diff
- fp.run(u.trajectory[i], lig, prot, progress=False)
+ fp.run(u.trajectory[i: (i+1)], lig, prot, progress=False)
```
or it will give you an error:

``` python
AttributeError: 'numpy.ndarray' object has no attribute 'frame'
```
Best wishes,

pineapple 🍍
