### ISSUE TITLE
Issue on page /source/modules/plotting.html barcode plot error

### ISSUE THREAD

**Issue by crisslind** [chemosim-lab/ProLIF#178]
I am trying to dplot the barcode - I can generate the image but get an error on line 159 in barcode.py with the ax.set_ticks
![Screenshot 2023-12-15 103704](https://github.com/chemosim-lab/ProLIF/assets/6592823/fe28fb08-d09c-46c0-98eb-ab9dac666384)
The dataframe looks fine
![Screenshot 2023-12-15 104123](https://github.com/chemosim-lab/ProLIF/assets/6592823/7deab1c4-7ea4-444d-949d-d38df9c7c343)
I get the same error if trying the example

**Comment by cbouy** [comment]
Sounds like a matplotlib version issue, which version are you on? It should be at least 3.5.0
