### ISSUE TITLE
Getting blured plot of Interactions Fingerprint and 2-D Interactions network. 

### ISSUE THREAD

**Issue by Anujkumarp** [chemosim-lab/ProLIF#183]
While plotting Fingerprint Interactions and 2-D Interactions network I am getting blured plots. 

![Screenshot 2024-01-11 194148](https://github.com/chemosim-lab/ProLIF/assets/125204395/4b8af4db-3ba0-4bea-a4af-b3b1f2c516af)

![Screenshot 2024-01-11 194306](https://github.com/chemosim-lab/ProLIF/assets/125204395/72def644-83f4-44da-b6e9-f228880775ac)

**Comment by cbouy** [comment]
That's odd, how are you generating the plots: from a Jupyter notebook, JupyterLab, Google Colab...etc.? Have you tried with a different web browser?

**Comment by Anujkumarp** [comment]
I have tried in both Jupyter Notebook as well as Jupyter Lab.

**Comment by Anujkumarp** [comment]
Thank you. I got it, I think there was some issue with my Anaconda Installation. I reinstalled it, and now I am getting clear plots.
