### ISSUE TITLE
how can i filter the results of fp 

### ISSUE THREAD

**Issue by hima111997** [chemosim-lab/ProLIF#184]
![image](https://github.com/chemosim-lab/ProLIF/assets/55895327/6d5e836f-8ce1-4862-acaa-dc929a738709)

how can i filter the results of interactions based on their proportion to enhance the plot?

**Comment by cbouy** [comment]
Hi,

You can directly filter the pandas DataFrame output by `fp.to_dataframe` and input that to the `Barcode` class (which is run under the hood when calling `fp.plot_barcode`).

Here's an example:
```python
from prolif.plotting.barcode import Barcode

# example: filter interaction that occur in less than 30% of frames
threshold = 0.3
df = fp.to_dataframe()
# only keep interactions occurring more frequently than the threshold
above_threshold_mask = df.mean() > threshold
df_filtered = df.loc[:, above_threshold_mask]
# plot
Barcode(df_filtered).display()
```

Feel free to reopen the issue if you have another related question

**Comment by Mishakolok** [comment]
Hello, I have tried to use the suggested solution, however, I get an error "KeyError: 'Level ligand not found'"
I think this happens because the df_filtered DataFrame does not have the first row with the name of the ligand. However, I don't have enough experience with Pandas to fix it straightaway.
