### ISSUE TITLE
Residue Numbers 

### ISSUE THREAD

**Issue by Anujkumarp** [chemosim-lab/ProLIF#186]
Actually, my protein structure had few missing residues in the beginning. Like from 1 to  4. While computing fingerprint Interactions it is  renumbering the residues. Because of that my residues numbers of  protein structure  are  changed. Now, GLU107 becomes GLU103, ALA74 becomes  ALA70 like that. Is there any way to correct it ?

**Comment by cbouy** [comment]
ProLIF just uses the residue numbers as parsed by MDAnalysis. If you do `u.residues.resids` you should see those "incorrect" numbers, but you can manipulate them as you want, i.e. `u.residues.resids += 4` should do the trick in your case.

Please close the issue if this solves your problem

**Comment by Anujkumarp** [comment]
Thank you for the support it works.
