### ISSUE TITLE
Random result of ifp?

### ISSUE THREAD

**Issue by tom832** [chemosim-lab/ProLIF#194]
When I use prolif to analyze the ifp of following receptor and ligand, it gave me different ifp results.
So is there any random module or algorithm in proliferation?
BTW, I use `plf.Fingerprint(count=True)` in my code.

receptor file: [7en8_clean_H.pdbfixer.pdb.txt](https://github.com/chemosim-lab/ProLIF/files/14613119/7en8_clean_H.pdbfixer.pdb.txt)

ligand file:[7en8_lig_H.sdf.txt](https://github.com/chemosim-lab/ProLIF/files/14613121/7en8_lig_H.sdf.txt)

**Comment by cbouy** [comment]
Well at least not intentionally. I gave your files a go and the results for 10 repeats are the exact same, are you sure you tried on the same python installation? Which version are you using?

**Comment by tom832** [comment]
I found it might be the random positions of added H with pdbfixer I used.
Have you ever found this issue? or how can I get solid added Hs positions?

**Comment by cbouy** [comment]
Ah right, then yes different H positions are going to affect the HBond detection.
Can't offer support for pdbfixer though, but hopefully there's a random seed that you can set there to help with that
