### ISSUE TITLE
Comparing fingerprints between trajectories 

### ISSUE THREAD

**Issue by erbb2** [chemosim-lab/ProLIF#20]
Hi,

I was successfully able to map out fingerprints of protein for a specific ligand. Now I have multiple proteins interacting with same ligand. How do I use something like Tanimoto coefficient to look at the similarities between these proteins?

**Comment by cbouy** [comment]
Hi @erbb2,

If your proteins are related to each other, you might replace the residue names and numbers in each interaction fingerprint by a generic residue numbering system (something like Ballesteros–Weinstein if you happen to work with GPCRs), or more simply by the column number from a multiple sequence alignment between your proteins.
Once you have a dictionary mapping the old residue names to the generic ones for each receptor, and you have converted the fingerprint to a pandas DataFrame (`df` in the example), you could do something like this:
```python
import prolif as plf
import pandas as pd
from rdkit.Chem import DataStructs

# do this for each fingerprint
df1 = fp.to_dataframe()
# old resids to generic naming system common to all your proteins
mapping = {
    "VAL201": 206,
    "HIS202": 208,
    # ...
} 
df1 = df1.rename(columns=mapping, level="protein")
# same with df2 to dfN for your N proteins

# concatenate all results
df = (
    pd.concat([
        df1.set_axis(["protein1"], axis=0), # replace protein1 by the name of your protein
        df2.set_axis(["protein2"], axis=0), # same here
        # add as many df3, df4...etc as you'd like
    ]).fillna(False)
)

# compute tanimoto similarity matrix
bvs = plf.to_bitvectors(df)
mat = []
for bv in bvs:
    mat.append(DataStructs.BulkTanimotoSimilarity(bv, bvs))
mat = pd.DataFrame(mat, index=df.index, columns=df.index)

print(mat)
```

Hope it helps,
Cédric

**Comment by erbb2** [comment]
Hi Cédric,

Thank you so much for the script. 
I have few queries regarding the fingerprint if possible can you please comment/discuss.

1. So here we are trying to consider all the interaction between the protein and ligand within 6A distance and then plot the time evolution interaction map. From literature what i have realized is fingerprint is a bit vector where u represent 0 and 1 for interaction absence and presence, there is no time factor here. So how can we call these interactions a
![test](https://user-images.githubusercontent.com/84761598/122968398-1d297500-d351-11eb-91b3-293f85797aa5.png)
![test1](https://user-images.githubusercontent.com/84761598/122968404-1f8bcf00-d351-11eb-9925-57449159f64d.png)
 fingerprint, what do you refer to?

2. i have below shown plot for same target with different ligand bound interaction plot. So there are some common residues between both. How do i characterize further to get an useful insight to their interactions? can you please highlight some tips.

3. Below is the code i used how do i change the y axis as u can see both the plots the axis get changed upside down everything time i plot. so its the same code once it writes 0-1000, next time it writes from 1000-0. how do i make this static. Also how do i change the frames to time scale for example to 100ns etc..

`sns.set_theme(font_scale=.8, style="white", context="talk")
g = sns.catplot(
    data=data, x="interaction", y="Frame", hue="interaction", col="residue",
    hue_order=["Hydrophobic", "HBDonor", "HBAcceptor", "PiStacking", "CationPi", "Cationic"],
    height=3, aspect=0.2, jitter=0, sharex=False, marker="_", s=8, linewidth=3.5,
)
g.set_titles("{col_name}")
g.set(xticks=[], ylim=(-.5, data.Frame.max()+1))
g.set_xticklabels([])
g.set_xlabels("")
g.fig.subplots_adjust(wspace=0)
g.add_legend()
g.despine(bottom=True)
for ax in g.axes.flat:
    ax.invert_yaxis()
    ax.set_title(ax.get_title(), pad=16, rotation=60, ha="center", va="baseline")`



Thank you
A
![test](https://user-images.githubusercontent.com/84761598/122968431-29adcd80-d351-11eb-92db-f306d70d0b7a.png)
![test1](https://user-images.githubusercontent.com/84761598/122968436-2adefa80-d351-11eb-9723-41b8bb6faa71.png)

**Comment by cbouy** [comment]
> So here we are trying to consider all the interaction between the protein and ligand within 6A distance and then plot the time evolution interaction map. From literature what i have realized is fingerprint is a bit vector where u represent 0 and 1 for interaction absence and presence, there is no time factor here. So how can we call these interactions a fingerprint, what do you refer to?

An interaction fingerprints (IFP) is indeed a bitvector of 0 and 1 for a specific conformation of your protein and ligand. When you run ProLIF on an MD trajectory, you get a collection of IFPs and usually output it as a dataframe, and each IFP is indexed by time "Frame". But ProLIF can also work with docking results where you obtain multiple conformations of your protein and ligand (there's no notion of time here), or even a crystallographic structure (no time either). But in all cases, it will output the same object: a dataframe of one or more IFPs.
   I tend to use the word "IFP" (or sometimes just fingerprint) for both a single or a collection of IFPs, when I usually mean "an IFP or collection of IFPs converted to a dataframe". Sorry if that's confusing! What you're showing in those plots is multiple IFPs technically.

---

> i have below shown plot for same target with different ligand bound interaction plot. So there are some common residues between both. How do i characterize further to get an useful insight to their interactions? can you please highlight some tips.

What you could do is basically compare a consensus IFP of each ligand:
- In the dataframe of a specific ligand (called df1):
```python
   threshold = 0.3  # keep if an interaction between a residue and the ligand happens more than 30% of the time
   frequency = df1.mean()
   df1_consensus= frequency.loc[frequency > threshold].to_frame().T
   df1_consensus.values[:] = 1
   df1_consensus.set_axis(["ligand_1"], axis=0, inplace=True)
```
You will get a dataframe with a single row and only "1" values where the interaction happened more than threshold. Do this for all your ligands (df2, ...etc.)
- Then you can compare the consensus IFPs with:
   ```python
   df = (
       pd.concat([
           df1_consensus,
           df2_consensus])
       .fillna(0)
       .astype(int))
   df.loc[:, df.nunique() > 1]
   print(df)
   ```
This will show where the consensus interactions differ and should help having a clearer picture of what's going on.

Alternatively, you could also use tanimoto similarity here (although it's not very practical if you have a lot of frames:
```python
df = pd.concat([
    df1.set_axis([f"lig1_{i}" for i in df1.index]),
    df2.set_axis([f"lig2_{i}" for i in df2.index]),
]).fillna(False)
from rdkit.Chem import DataStructs
bvs = plf.to_bitvectors(df)
mat = []
for bv in bvs:
    mat.append(DataStructs.BulkTanimotoSimilarity(bv, bvs))
mat = pd.DataFrame(mat, index=df.index, columns=df.index)
import seaborn as sns
import matplotlib.pyplot as plt
fig, ax = plt.subplots(figsize=(3, 3), dpi=200)
sns.heatmap(
    mat, ax=ax, square=True,
    cmap="icefire",
    vmin=0, vmax=1, center=.6,
)
ax.invert_yaxis()
fig.patch.set_facecolor('white')
```
It will plot a heatmap of the tanimoto matrix

---

> Below is the code i used how do i change the y axis as u can see both the plots the axis get changed upside down everything time i plot. so its the same code once it writes 0-1000, next time it writes from 1000-0. how do i make this static. Also how do i change the frames to time scale for example to 100ns etc..

This is weird it should be static, and I cannot reproduce the issue with the inverted order so I can't really help here :/
For using the time scale:
```python
df.index = pd.Series([ts.time for ts in u.trajectory], name="Time")  # make sure you use the same u.trajectory as in the fp.run
data = df.reset_index()
data = pd.melt(data, id_vars=["Time"], var_name=["residue","interaction"])
# ... make sure to change "Frame" by "Time" in the rest of the code
```
The units used should be the one available in u.trajectory.units

---
PS: to show long snippets of code use
````
```python
print("hello world")
```
````

**Comment by erbb2** [comment]
Hi,

Thank you so much clearing my doubts, Am trying the ways you have mentioned.
For the time factor, ie having the plot with Time regime and not frame, i did the way you have metioned previously but i get few errors, can you please help me to resolve them. Below is the error:

axisgrid.py:64: UserWarning: Tight layout not applied. The left and right margins cannot be made large enough to accommodate all axes decorations. 
  self.fig.tight_layout(*args, **kwargs)
axisgrid.py:64: UserWarning: Tight layout not applied. The left and right margins cannot be made large enough to accommodate all axes decorations. 
  self.fig.tight_layout(*args, **kwargs)
Traceback (most recent call last):
  File "code_prolif.py", line 38, in <module>
    g.set(xticks=[], ylim=(-.5, data.Frame.max()+1))
  File "generic.py", line 5465, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'Frame'

Am also mentioning the code :


```pythonimport MDAnalysis as mda
import prolif as plf
from rdkit import Chem
from rdkit.Chem import Draw
import seaborn as sns
import pandas as pd
# load trajectory
u = mda.Universe('md.tpr', 'md.xtc')
# create selections for the ligand and protein
lig = u.atoms.select_atoms("resname LIG")
prot = u.atoms.select_atoms("protein")
lig, prot
# use default interactions
fp = plf.Fingerprint()
# run on a slice of frames from begining to end with a step of 10
#fp.run(u.trajectory[::1000], lig, prot)
fp.run(u.trajectory[::1000], lig, prot, residues=["PRO28","THR29","SER31","TRP80","SER176","ILE177","MET179","PRO180","GLN186","ARG187","LEU188","PHE190"])
df = fp.to_dataframe()
df.index = pd.Series([ts.time for ts in u.trajectory[::1000]], name="Time")  # make sure you use the same u.trajectory as in the fp.run
data = df.reset_index()
data = pd.melt(data, id_vars=["Time"], var_name=["residue","interaction"])
# drop the ligand residue column since there's only a single ligand residue
df = df.droplevel("ligand", axis=1)
# reorganize data
#data = df.reset_index()
#data = pd.melt(data, id_vars=["Frame"], var_name=["residue","interaction"])
data = data[data["value"] != False]
data.reset_index(inplace=True, drop=True)# plot
sns.set_theme(font_scale=.8, style="white", context="talk")
g = sns.catplot(
    data=data, x="interaction", y="Time", hue="interaction", col="residue",
    hue_order=["Hydrophobic", "HBDonor", "HBAcceptor", "PiStacking", "CationPi", "Cationic"],
    height=3, aspect=0.2, jitter=0, sharex=False, marker="_", s=8, linewidth=3.5,
)
g.set_titles("{col_name}")
g.set(xticks=[], ylim=(-.5, data.Frame.max()+1))
g.set_xticklabels([])
g.set_xlabels("")
g.fig.subplots_adjust(wspace=0)
g.add_legend()
g.despine(bottom=True)
for ax in g.axes.flat:
    ax.invert_yaxis()
    ax.set_title(ax.get_title(), pad=16, rotation=60, ha="center", va="baseline")
g.savefig('test.png')
```

Please let me knw were i have gone wrong with this.

Your help has been really appreciated.

thank you

**Comment by cbouy** [comment]
`g.set(xticks=[], ylim=(-.5, data.Frame.max()+1))` should be
`g.set(xticks=[], ylim=(-.5, data["Time"].max()+1)) `
