### ISSUE TITLE
Ifs for ligands without explicit Hs in the file

### ISSUE THREAD

**Issue by Lili-Cao** [chemosim-lab/ProLIF#213]
Hi,

I am wondering how is the interaction fps generated when there is no explicit Hs in the ligand structure file.
I used NoImplicit=False in ref_mol = plf.Molecule.from_mda(u1, NoImplicit=False) and get 
"Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 6 8 9" warning. Could you please tell me how to solve this?

However, I get Hbond receptor and donor detected but I am wondering how it is working as there is no H atoms? 

Thanks!
Lili

**Comment by cbouy** [comment]
Hi,

ProLIF does not add any hydrogen atom, if your ligand file has no hydrogen atom it should not be able to detect HBDonor interactions (the SMARTS pattern requires explicit hydrogens on the ligand for that one).

Using `NoImplicit=False` parameter should only be needed if the algorithm used by MDAnalysis to infer bond orders and charges from the topology with explicit H fails for whatever reason and you need to manually adjust the resulting raw rdkit molecule before passing it to ProLIF (using RDKit's `AllChem.BondOrdersFromTemplate` for example).

Are you absolutely certain that there are none in your file?

**Comment by cbouy** [comment]
Closing the issue since no feedback, feel free to reopen with more info
