### ISSUE TITLE
Wrong 2D depiction of alkyl structures caused by rdkit.

### ISSUE THREAD

**Issue by alchemistcai** [chemosim-lab/ProLIF#215]
It has solved by myself and not caused by prolif directly.But I create this issue since I don't see similar questions in prolif's repo.

#### issue

When using `Fingerprint.plot_lignetwork` to show 2D interaction,alkyl substructures become linear,whatever `use_coordinates` is True or False.

![屏幕截图_20240823_141131](https://github.com/user-attachments/assets/c48b33d9-8e27-4ab6-9aba-6778b8276acd)

#### troubleshooting

Use rdkit's CoordGen support to create a more reasonable 2D image.

```py
from rdkit.Chem import rdDepictor
rdDepictor.SetPreferCoordGen(True) # use CoordGen library to calculate coordinates
fp.plot_lignetwork(ligand_mol,rotation=130) # need to set rotation manually,maybe also need to drage interaction edges too.
```

![屏幕截图_20240823_141532](https://github.com/user-attachments/assets/ba31083b-8124-49fb-ba6d-2bfc1ec5e483)

#### related link

[rdkit:Incorrect drawing of E/Z stereoisomers](https://github.com/rdkit/rdkit/issues/4180)

Contributors of rdkit think that CoordGen beats rdDepictor's default algorithm in accuracy along with lower efficiency.

**Comment by cbouy** [comment]
Thanks a lot @alchemistcai for mentioning this, I'm sure it will help other users!

I'll just add that you can also directly set 2D coordinates on the `ligand_mol` and have ProLIF use them directly by passing `use_coordinates=True, flatten_coordinates=False` to the plotting function e.g. if you want to display multiple ligands that share a common core by aligning them on their MCS before plotting.
