### ISSUE TITLE
Turn off pseudobonds

### ISSUE THREAD

**Issue by ONISniperOne** [chemosim-lab/ProLIF#217]
Is there a way to turn off pseudobond drawing when comparing frames or even when drawing one frame? Still want to keep the difference highlighting (magenta coloring)

![image](https://github.com/user-attachments/assets/8832ef0d-a8b1-4e3b-b7d0-9b7bd39f874f)

**Comment by cbouy** [comment]
Hi,

Yes, you can do this like so:
```python
view = comp3D.compare(other_comp3D)
# get py3dmol view object (compatibility with upcoming ProLIF version)
v = getattr(view, "_view", view)
# remove all cylinder shapes
v.removeAllShapes()
view
```

Feel free to reopen this issue if you have another related question.

Cheers,
Cédric
