### ISSUE TITLE
Regarding selection of Groups to calculate the distance for an interaction. 

### ISSUE THREAD

**Issue by Anujkumarp** [chemosim-lab/ProLIF#218]
Dear Sir, Good Morning

I have query related to the atoms/groups selection in ProLIF for FI computation. Can you please tell when we measure the distance between the protein and ligand, which atoms/groups determine the centers (of mass or geometry), the head group? the side chain group ? 

Thanks & Regards 
Anuj Kumar

**Comment by cbouy** [comment]
Hi @Anujkumarp 

Not sure I fully understood the question, but if you mean which are the atoms that are used for checking the distance threshold criteria for the different kinds of interactions:
- Hydrogen bonds: the acceptor and donor atom (i.e. not the hydrogen)
- Halogen bonds (XB): the acceptor and halogen atom
- Cation-pi: the cation and the center of geometry of the ring system atoms (for fused rings its one of the 5 or 6 membered rings)
- pi-stacking: the center of geometry of the ring system atoms (same rule as above for fused rings)
- for hydrophobic, ionic and metal coordination: any atom that satisfies the SMARTS pattern defined in [this section of the documentation](https://prolif.readthedocs.io/en/stable/source/modules/interaction-fingerprint.html#detecting-interactions-between-residues-prolif-interactions-interactions)

ProLIF doesn't have any notion of backbone/side-chain, it's meant to be agnostic of the kind of system you're investigating (so host-guest systems, materials, DNA-protein...etc. should all work with ProLIF).

If this doesn't answer your question or you have another related question, feel free to reopen the issue.

Best regards,
Cédric
