### ISSUE TITLE
Is it possible to get only sidechain-sidechain interaction fingerprint?

### ISSUE THREAD

**Issue by soumyosen** [chemosim-lab/ProLIF#22]
I am trying to get the protein-protein interaction fingerprint. But I would like to limit it to sidechain-sidechain interaction. I used the following script. But I don't think it is working. Is there any other way or is it possible?

> import MDAnalysis as mda
> import prolif
> import pandas as pd
> u1 = mda.Universe("last_frame_wild_noion1.pdb")
> u1.atoms.guess_bonds()
> prot1 = u1.select_atoms("same residue as protein and not (segid A and resid 771) and not backbone and around 10.0 (segid A and resid 771)")
> lig1 = u1.select_atoms("segid A and resid 771 and not backbone")
> fp = prolif.Fingerprint(interactions="all")
> df1 = fp.run(u1.trajectory[:], lig1, prot1).to_dataframe()
> df1.head()

Soumyo

**Comment by cbouy** [comment]
Hi @soumyosen,

Unfortunately, if you exclude backbone atoms when you make the selection (prot1 and lig1 in your code), at some point in the code prolif tries to infer bond orders and charges for both molecules but since they are missing the bonds to the backbone, it will result in incorrectly charged molecules where the bonds are lacking.
You can visualize this with
```python
from rdkit.Chem import Draw
mol = plf.Molecule.from_mda(lig1)
mol.RemoveAllConformers()
Draw.MolToImage(mol, size=(400, 300))
```
And it should show some charged atoms at the connection where the backbone is supposed to be.

Here is an alternative that should work (although its a bit more complicated):
```python
from rdkit.Chem import AllChem
# make selection (keep backbone for now)
prot1 = u1.select_atoms("same residue as protein and not (segid A and resid 771) and around 10.0 (segid A and resid 771)")
lig1 = u1.select_atoms("segid A and resid 771")
prot_mol = plf.Molecule.from_mda(prot1)
lig_mol = plf.Molecule.from_mda(lig1)
# remove backbone
backbone = Chem.MolFromSmarts("[C^2](=O)-[C;X4](-[H])-[N;+0]-[H]")
lig_mol = AllChem.DeleteSubstructs(lig_mol, backbone)
prot_mol = AllChem.DeleteSubstructs(prot_mol, backbone)
# generate IFP
data = fp.generate(lig_mol, prot_mol)
data["Frame"] = 0
ifp = [data]
df1 = plf.to_dataframe(ifp, fp.interactions.keys())
```

PS: the SMARTS selection for the backbone will not remove backbone atoms for proline residues, you will need a separate SMARTS for that

**Comment by cbouy** [comment]
Small correction:
add `mol = plf.Molecule(mol)` right after removing the backbone with `AllChem.DeleteSubstructs` (updated my previous post)

**Comment by soumyosen** [comment]
Thank you for your help. I will try and let you know.

**Comment by soumyosen** [comment]
OK, so I used the following script

> import MDAnalysis as mda
> import prolif
> import pandas as pd
> from rdkit.Chem import AllChem
> from rdkit import Chem
> 
> u1 = mda.Universe("last_frame_wild_noion1.pdb")
> u2 = mda.Universe("last_frame_mutate_new_noion.pdb")
> 
> u1.atoms.guess_bonds()
> u2.atoms.guess_bonds()
> 
> prot1 = u1.select_atoms("same residue as protein and not (segid A and resid 771) and not backbone and around 10.0 (segid A and resid 771 and not backbone)")
> lig1 = u1.select_atoms("segid A and resid 771")
> prot1, lig1
> 
> prot1_mol = prolif.Molecule.from_mda(prot1)
> lig1_mol = prolif.Molecule.from_mda(lig1)
> backbone = Chem.MolFromSmarts("[C^2](=O)-[C;X4](-[H])-[N;+0]-[H]")
> lig1_mol = AllChem.DeleteSubstructs(lig1_mol, backbone)
> lig1_mol = prolif.Molecule(lig1_mol)
> prot1_mol = AllChem.DeleteSubstructs(prot1_mol, backbone)
> prot1_mol = prolif.Molecule(prot1_mol)
> 
> fp = prolif.Fingerprint(interactions="all")
> data = fp.generate(lig1_mol, prot1_mol)

Here I am getting en error. Message is 
> 'Fingerprint' object has no attribute 'generate'

**Comment by cbouy** [comment]
@soumyosen you need to update to the latest version (v0.3.3) `pip install https://github.com/chemosim-lab/ProLIF/archive/v0.3.3.zip`, sorry for the inconvenience!

**Comment by soumyosen** [comment]
Thank you, it works now.
