### ISSUE TITLE
Show percentage of interaction in lignetwork

### ISSUE THREAD

**Issue by sperezconesa** [chemosim-lab/ProLIF#226]
Hello,

Would it be possible to add to the `fp.plot_lignetwork` labels to the interactions with the frequency percentage. The intensity of the color is nice but the number would be ideal. Perhaps with a button to turn it off if it is too messy.

Love the work you have  done with this code!

Thanks!
Sergio

**Comment by cbouy** [comment]
Should be doable, [this line](https://github.com/chemosim-lab/ProLIF/blob/master/prolif/plotting/network.py#L583) defines the label and there's a `weight` variable that contains that info so it's just a matter of changing that line to include the info e.g. `f"{interaction}: {distance:.2f}Å ({weight * 100:.0f}%)"`

**Comment by talagayev** [comment]
> Should be doable, [this line](https://github.com/chemosim-lab/ProLIF/blob/master/prolif/plotting/network.py#L583) defines the label and there's a `weight` variable that contains that info so it's just a matter of changing that line to include the info e.g. `f"{interaction}: {distance:.2f}Å ({weight * 100:.0f}%)"`

I could try to implement it, since I have some free time in the next weeks if you would want to have the percentage label in there and then create a PR for it :)

**Comment by cbouy** [comment]
Please do! Should be pretty quick to review on my side

**Comment by talagayev** [comment]
> Please do! Should be pretty quick to review on my side

Perfect, will do it in the upcoming days :)

**Comment by sperezconesa** [comment]
Thank you! This is very useful. I have actually tried the code. 

What I was actually referring to is the number showing up in the middle of the edge all the time or that it could be toggled off with a button. This solution gives most of what I was looking for though.

**Comment by cbouy** [comment]
If you install from the master branch directly you can now access this change by specifying `show_interaction_data=True` in `fp.plot_lignetwork`.

If you need more customisation you can also modify the label and hover title themselves by using the underlying `LigNetwork` class directly:
```python
from prolif.plotting.network import LigNetwork

lignetwork = LigNetwork.from_fingerprint(fp, ligand_mol)
lignetwork._edge_title_formatter = "{interaction}: {distance:.2f}Å"  # default
lignetwork._edge_label_formatter = "{weight_pct:.0f}%"  # default
lignetwork.display(show_interaction_data=True)
```
