### ISSUE TITLE
[Feature Request] K means clustering

### ISSUE THREAD

**Issue by ONISniperOne** [chemosim-lab/ProLIF#231]
Is there a way to implement K means clustering analysis to the tanimoto matrix? I was thinking of using the NANI method to get specific frame #s
https://pubs.acs.org/doi/10.1021/acs.jctc.4c00308

and then exporting those frames to get separate MM/GBSA scores during downstream analysis

**Comment by cbouy** [comment]
I think you can simply convert the dataframe from prolif to a numpy array, and then directly use that as input to [NANI](https://mdance.readthedocs.io/en/latest/api.html#module-mdance.cluster.nani) specifying `metric="JT"` for Tanimoto

**Comment by ONISniperOne** [comment]
Thanks! I'll check it out XD

**Comment by ONISniperOne** [comment]
Thanks! I'll check it out XD
