### ISSUE TITLE
Question about the method plot_3d

### ISSUE THREAD

**Issue by xavgit** [chemosim-lab/ProLIF#232]
Hi, 
regarding the code in the tutorial:
view = fp_count.plot_3d(
    pose_iterable[pose_index], protein_mol, frame=pose_index, display_all=False
)
view
how it is possible to instruct pymol3D to visualize only the ligand, the receptor residues interacting with the ligand and the interactions without the "ribbon" of all the other residue of the receptor to make the visualization focused on the essential information about the interaction ligand-receptor?

Thanks.

Saverio

**Comment by cbouy** [comment]
Hi Saverio,
You can set the style of the entire protein with:

```python
from prolif.plotting.complex3d import Complex3D

Complex3D.PROTEIN_STYLE = {}  # default: {"cartoon": {"style": "edged"}}
```
and then call `fp_count.plot_3d`

Feel free to re-open if you have any other related questions!
