### ISSUE TITLE
Missing side chain and interactions 

### ISSUE THREAD

**Issue by ONISniperOne** [chemosim-lab/ProLIF#233]
Protein side chain missing in interaction with ligand
![image](https://github.com/user-attachments/assets/c23dc2d4-cc32-4cf6-86b9-e9f98e63a84c)

Also missing many interactions found in other software like ChimeraX (contacts command)
![image](https://github.com/user-attachments/assets/0144e0e0-d8db-4797-874d-2ab62b890133)
vs
![image](https://github.com/user-attachments/assets/4628e5a6-1e44-44a9-998a-7a5db818a55d)

Most worrying is the lack of interactions around the naphthyl sulfonamide group

**Comment by cbouy** [comment]
Hi @ONISniperOne 

Hard to tell without a bit more info. Can you share the script you used for the first visualization that is missing the residue?

For the comparison with Chimera, could you pick one interaction from Chimera and share the distance and which elements are involved?

**Comment by ONISniperOne** [comment]
Here's the script

# import
import MDAnalysis as mda
import prolif as plf
from rdkit import Chem
from rdkit.Chem.AllChem import AssignBondOrdersFromTemplate
import subprocess
import matplotlib.pyplot as plt

# Prepare protein
# Run the Open Babel command to protonate the protein
subprocess.run(
    "pdb4amber example_protein.pdb > example_protein_with_H.pdb --reduce",
    shell=True,
    check=True
)

protein_file = "example_protein_with_H.pdb" # Protein must be protonated. Usually pdb's are not protonated.

u = mda.Universe(protein_file)
protein_mol = plf.Molecule.from_mda(u)
protein_mol.n_residues

# Prepare ligand version 2

# Run the Open Babel command to protonate the ligand pdb > sdf
subprocess.run(
    "obabel -ipdb example_ligand.pdb -osdf -h -O example_ligand_2_with_H.sdf",
    shell=True,
    check=True
)

ligand_file = "example_ligand_2_with_H.sdf"
ligand_mol = plf.sdf_supplier(ligand_file)[0]
# display ligand
plf.display_residues(ligand_mol, size=(400, 200))

# Analyze the interactions between ligand and protein

fp_count = plf.Fingerprint(count=True)
fp_count.run_from_iterable([ligand_mol], protein_mol)

# 2D ligplot
fp_count.plot_lignetwork(ligand_mol, kind="frame", frame=0, display_all=True)


# 3D version

view = fp_count.plot_3d(ligand_mol, protein_mol, frame=0, display_all=True)
view

**Comment by ONISniperOne** [comment]
And here's a list of interactions detected b/w the protonated ligand and protein

Allowed overlap: -0.4
H-bond overlap reduction: 0.4
Ignore contacts between atoms separated by 4 bonds or less
Detect intra-residue contacts: False
Detect intra-molecule contacts: False

101 contacts
                   atom1                                    atom2                overlap  distance
example_protein_with_H.pdb #1/A SER 113 H     example_ligand.pdb #2/? UNL 1 H49   0.641    1.359
example_protein_with_H.pdb #1/A TRP 112 HA    example_ligand.pdb #2/? UNL 1 H49   0.516    1.484
example_protein_with_H.pdb #1/A SER 113 H     example_ligand.pdb #2/? UNL 1 O14   0.484    1.616
example_protein_with_H.pdb #1/A TYR 53 H      example_ligand.pdb #2/? UNL 1 H42   0.465    1.535
example_protein_with_H.pdb #1/A SER 113 N     example_ligand.pdb #2/? UNL 1 H49   0.441    2.184
example_protein_with_H.pdb #1/A ARG 51 CG     example_ligand.pdb #2/? UNL 1 H41   0.380    2.320
example_protein_with_H.pdb #1/A ARG 51 CB     example_ligand.pdb #2/? UNL 1 H41   0.367    2.333
example_protein_with_H.pdb #1/A TYR 53 H      example_ligand.pdb #2/? UNL 1 O3    0.363    1.737
example_protein_with_H.pdb #1/A ARG 51 CD     example_ligand.pdb #2/? UNL 1 H41   0.346    2.354
example_protein_with_H.pdb #1/A ARG 51 HD3    example_ligand.pdb #2/? UNL 1 H41   0.335    1.665
example_protein_with_H.pdb #1/A ARG 51 HB3    example_ligand.pdb #2/? UNL 1 H41   0.330    1.670
example_protein_with_H.pdb #1/A TRP 112 CA    example_ligand.pdb #2/? UNL 1 H49   0.313    2.387
example_protein_with_H.pdb #1/A LYS 115 HB2   example_ligand.pdb #2/? UNL 1 O15   0.220    2.280
example_protein_with_H.pdb #1/A GLN 117 OE1   example_ligand.pdb #2/? UNL 1 O16   0.219    2.761
example_protein_with_H.pdb #1/A LYS 111 O     example_ligand.pdb #2/? UNL 1 H39   0.214    1.866
example_protein_with_H.pdb #1/A TRP 112 HA    example_ligand.pdb #2/? UNL 1 O14   0.200    2.300
example_protein_with_H.pdb #1/A TYR 53 N      example_ligand.pdb #2/? UNL 1 H42   0.194    2.431
example_protein_with_H.pdb #1/A SER 113 N     example_ligand.pdb #2/? UNL 1 O14   0.165    2.560
example_protein_with_H.pdb #1/A ARG 51 HB3    example_ligand.pdb #2/? UNL 1 O2    0.154    2.346
example_protein_with_H.pdb #1/A ARG 51 CB     example_ligand.pdb #2/? UNL 1 O2    0.135    3.065
example_protein_with_H.pdb #1/A ARG 104 HH22  example_ligand.pdb #2/? UNL 1 O8    0.133    1.967
example_protein_with_H.pdb #1/A TYR 120 HB3   example_ligand.pdb #2/? UNL 1 H30   0.127    1.873
example_protein_with_H.pdb #1/A PRO 52 N      example_ligand.pdb #2/? UNL 1 O3    0.114    3.011
example_protein_with_H.pdb #1/A GLN 117 OE1   example_ligand.pdb #2/? UNL 1 C26   0.113    3.067
example_protein_with_H.pdb #1/A TYR 120 CB    example_ligand.pdb #2/? UNL 1 H30   0.111    2.589
example_protein_with_H.pdb #1/A PRO 52 CD     example_ligand.pdb #2/? UNL 1 O3    0.093    3.107
example_protein_with_H.pdb #1/A ARG 51 CG     example_ligand.pdb #2/? UNL 1 O2    0.084    3.116
example_protein_with_H.pdb #1/A TYR 2 HD1     example_ligand.pdb #2/? UNL 1 C34   0.076    2.624
example_protein_with_H.pdb #1/A ARG 51 HB3    example_ligand.pdb #2/? UNL 1 S1    0.074    2.708
example_protein_with_H.pdb #1/A ARG 104 HH12  example_ligand.pdb #2/? UNL 1 C15   0.056    2.644
example_protein_with_H.pdb #1/A ARG 51 HB3    example_ligand.pdb #2/? UNL 1 H42   0.050    1.950
example_protein_with_H.pdb #1/A TRP 112 CA    example_ligand.pdb #2/? UNL 1 O14   0.042    3.158
example_protein_with_H.pdb #1/A TRP 112 C     example_ligand.pdb #2/? UNL 1 H49   0.022    2.678
example_protein_with_H.pdb #1/A ARG 104 HH22  example_ligand.pdb #2/? UNL 1 H45   0.008    1.992
example_protein_with_H.pdb #1/A ARG 51 HB3    example_ligand.pdb #2/? UNL 1 O3    0.005    2.495
example_protein_with_H.pdb #1/A ARG 51 HD3    example_ligand.pdb #2/? UNL 1 O2    0.001    2.499
example_protein_with_H.pdb #1/A TYR 2 CD1     example_ligand.pdb #2/? UNL 1 C34   -0.015    3.415
example_protein_with_H.pdb #1/A TYR 120 CD2   example_ligand.pdb #2/? UNL 1 H30   -0.025    2.725
example_protein_with_H.pdb #1/A TYR 53 N      example_ligand.pdb #2/? UNL 1 O3    -0.032    2.757
example_protein_with_H.pdb #1/A GLN 117 OE1   example_ligand.pdb #2/? UNL 1 C25   -0.038    3.218
example_protein_with_H.pdb #1/A TYR 120 HB3   example_ligand.pdb #2/? UNL 1 C29   -0.043    2.743
example_protein_with_H.pdb #1/A ARG 51 CD     example_ligand.pdb #2/? UNL 1 O2    -0.051    3.251
example_protein_with_H.pdb #1/A ARG 51 C      example_ligand.pdb #2/? UNL 1 O3    -0.070    3.270
example_protein_with_H.pdb #1/A SER 113 O     example_ligand.pdb #2/? UNL 1 O15   -0.070    3.050
example_protein_with_H.pdb #1/A TRP 112 C     example_ligand.pdb #2/? UNL 1 O14   -0.071    3.271
example_protein_with_H.pdb #1/A LYS 115 O     example_ligand.pdb #2/? UNL 1 H31   -0.077    2.557
example_protein_with_H.pdb #1/A TYR 53 HB2    example_ligand.pdb #2/? UNL 1 O3    -0.081    2.581
example_protein_with_H.pdb #1/A SER 113 H     example_ligand.pdb #2/? UNL 1 C23   -0.083    2.783
example_protein_with_H.pdb #1/A LYS 111 O     example_ligand.pdb #2/? UNL 1 N2    -0.089    2.794
example_protein_with_H.pdb #1/A LYS 111 O     example_ligand.pdb #2/? UNL 1 H24   -0.095    2.575
example_protein_with_H.pdb #1/A PRO 52 HD2    example_ligand.pdb #2/? UNL 1 O3    -0.112    2.612
example_protein_with_H.pdb #1/A GLN 117 CD    example_ligand.pdb #2/? UNL 1 C26   -0.116    3.516
example_protein_with_H.pdb #1/A TYR 120 CG    example_ligand.pdb #2/? UNL 1 H30   -0.118    2.818
example_protein_with_H.pdb #1/A TRP 112 HE3   example_ligand.pdb #2/? UNL 1 C20   -0.123    2.823
example_protein_with_H.pdb #1/A LYS 111 O     example_ligand.pdb #2/? UNL 1 C21   -0.149    3.329
example_protein_with_H.pdb #1/A ARG 104 NH2   example_ligand.pdb #2/? UNL 1 O8    -0.150    2.875
example_protein_with_H.pdb #1/A ARG 104 HH12  example_ligand.pdb #2/? UNL 1 O8    -0.150    2.250
example_protein_with_H.pdb #1/A TYR 2 CD1     example_ligand.pdb #2/? UNL 1 C33   -0.152    3.552
example_protein_with_H.pdb #1/A LYS 115 CB    example_ligand.pdb #2/? UNL 1 O15   -0.156    3.356
example_protein_with_H.pdb #1/A TYR 120 CB    example_ligand.pdb #2/? UNL 1 C29   -0.161    3.561
example_protein_with_H.pdb #1/A LYS 115 O     example_ligand.pdb #2/? UNL 1 C30   -0.162    3.342
example_protein_with_H.pdb #1/A ARG 51 C      example_ligand.pdb #2/? UNL 1 H42   -0.166    2.866
example_protein_with_H.pdb #1/A GLN 117 HB3   example_ligand.pdb #2/? UNL 1 C28   -0.176    2.876
example_protein_with_H.pdb #1/A PRO 52 CG     example_ligand.pdb #2/? UNL 1 O3    -0.179    3.379
example_protein_with_H.pdb #1/A ARG 51 CB     example_ligand.pdb #2/? UNL 1 H42   -0.190    2.890
example_protein_with_H.pdb #1/A ARG 104 CZ    example_ligand.pdb #2/? UNL 1 O8    -0.196    3.396
example_protein_with_H.pdb #1/A ARG 51 HG2    example_ligand.pdb #2/? UNL 1 H41   -0.208    2.208
example_protein_with_H.pdb #1/A TYR 53 HB2    example_ligand.pdb #2/? UNL 1 O4    -0.208    2.708
example_protein_with_H.pdb #1/A SER 113 O     example_ligand.pdb #2/? UNL 1 H28   -0.215    2.695
example_protein_with_H.pdb #1/A TYR 120 CD2   example_ligand.pdb #2/? UNL 1 C29   -0.217    3.617
example_protein_with_H.pdb #1/A ARG 51 CB     example_ligand.pdb #2/? UNL 1 S1    -0.220    3.702
example_protein_with_H.pdb #1/A ARG 51 CB     example_ligand.pdb #2/? UNL 1 O3    -0.223    3.423
example_protein_with_H.pdb #1/A ARG 51 HG2    example_ligand.pdb #2/? UNL 1 O2    -0.226    2.726
example_protein_with_H.pdb #1/A TYR 53 CB     example_ligand.pdb #2/? UNL 1 O3    -0.228    3.428
example_protein_with_H.pdb #1/A TYR 120 CB    example_ligand.pdb #2/? UNL 1 H35   -0.229    2.929
example_protein_with_H.pdb #1/A PRO 52 HG2    example_ligand.pdb #2/? UNL 1 O3    -0.250    2.750
example_protein_with_H.pdb #1/A TRP 112 CE3   example_ligand.pdb #2/? UNL 1 H25   -0.258    2.958
example_protein_with_H.pdb #1/A LYS 111 O     example_ligand.pdb #2/? UNL 1 C18   -0.259    3.439
example_protein_with_H.pdb #1/A GLN 117 OE1   example_ligand.pdb #2/? UNL 1 S2    -0.265    3.527
example_protein_with_H.pdb #1/A TRP 112 HE3   example_ligand.pdb #2/? UNL 1 H21   -0.272    2.272
example_protein_with_H.pdb #1/A TYR 2 HD1     example_ligand.pdb #2/? UNL 1 C28   -0.297    2.997
example_protein_with_H.pdb #1/A ARG 104 NH1   example_ligand.pdb #2/? UNL 1 C15   -0.302    3.627
example_protein_with_H.pdb #1/A TYR 2 CD1     example_ligand.pdb #2/? UNL 1 C28   -0.306    3.706
example_protein_with_H.pdb #1/A TYR 53 H      example_ligand.pdb #2/? UNL 1 S1    -0.306    3.088
example_protein_with_H.pdb #1/A TRP 112 CE3   example_ligand.pdb #2/? UNL 1 C20   -0.318    3.718
example_protein_with_H.pdb #1/A GLN 117 HB3   example_ligand.pdb #2/? UNL 1 C29   -0.321    3.021
example_protein_with_H.pdb #1/A PRO 52 N      example_ligand.pdb #2/? UNL 1 H42   -0.328    2.953
example_protein_with_H.pdb #1/A SER 113 H     example_ligand.pdb #2/? UNL 1 C24   -0.342    3.042
example_protein_with_H.pdb #1/A ARG 104 NH2   example_ligand.pdb #2/? UNL 1 H45   -0.349    2.974
example_protein_with_H.pdb #1/A ARG 104 NH1   example_ligand.pdb #2/? UNL 1 O8    -0.351    3.076
example_protein_with_H.pdb #1/A ARG 51 CA     example_ligand.pdb #2/? UNL 1 O3    -0.357    3.557
example_protein_with_H.pdb #1/A LYS 111 C     example_ligand.pdb #2/? UNL 1 H39   -0.357    3.057
example_protein_with_H.pdb #1/A TYR 53 HB2    example_ligand.pdb #2/? UNL 1 S1    -0.361    3.143
example_protein_with_H.pdb #1/A ARG 104 HH12  example_ligand.pdb #2/? UNL 1 O7    -0.363    2.443
example_protein_with_H.pdb #1/A TYR 120 HD2   example_ligand.pdb #2/? UNL 1 H30   -0.370    2.370
example_protein_with_H.pdb #1/A GLN 117 CD    example_ligand.pdb #2/? UNL 1 C27   -0.374    3.774
example_protein_with_H.pdb #1/A TYR 2 HB3     example_ligand.pdb #2/? UNL 1 C33   -0.383    3.083
example_protein_with_H.pdb #1/A TYR 2 HD1     example_ligand.pdb #2/? UNL 1 C33   -0.390    3.090
example_protein_with_H.pdb #1/A TYR 53 HB2    example_ligand.pdb #2/? UNL 1 H42   -0.392    2.392
example_protein_with_H.pdb #1/A SER 113 H     example_ligand.pdb #2/? UNL 1 H28   -0.396    2.396
example_protein_with_H.pdb #1/A GLN 117 CB    example_ligand.pdb #2/? UNL 1 C29   -0.396    3.796

101 contacts

![image](https://github.com/user-attachments/assets/aa9dc7c8-85d5-4a30-b668-7b044276bcc7)

**Comment by ONISniperOne** [comment]
Also, there are some H bonds (blue) detected. The green bonds in earlier pictures are a catch all for all types of contacts - VDW, ionic bonds, hbonds, clashes, etc.
![image](https://github.com/user-attachments/assets/2d4da821-9a77-4212-bc0d-1efdd757ef55)
Hbond = blue, distance measurement = yellow

**Comment by ONISniperOne** [comment]
@cbouy Would it help if I provided the pdb's somehow?

**Comment by cbouy** [comment]
Yes please, some of the angles might be out of bounds. As for the visual issue, not sure what's causing this but with the PDBs it might help as well

**Comment by ONISniperOne** [comment]
[system.zip](https://github.com/user-attachments/files/18186122/system.zip)

- example_user_providedPDB = pdb containing both ligand & protein (unprotonated)
- exampe_ligand = pdb of only unprotonated ligand
- example_ligand_2_with_H.sdf = sdf file of protonated ligand produced while running jupyter notebook
- example_protein = pdb of only unprotonated protein
- example+protein_with_H = pdb of protonated protein produced while running jupyter notebook
- ligplot.ipynb = jupyter notebook with saved outputs

**Comment by cbouy** [comment]
There's a disulfide bridge in the prepared protein file so a `CONECT` record is added, which means MDAnalysis won't try to guess the remaining bonds (it only does so when there are no bonds present).
You need to force it to guess by specifying `u = mda.Universe(protein_file, guess_bonds=True)` and it works as expected after that.
You could also potentially use ` --no-conect` in `pdb4amber` to avoid writing the CONECT record.

Closing the issue but feel free to add any comment

**Comment by ONISniperOne** [comment]
Thanks! It works perfectly now. Told MDAnalysis to guess the bonds
