### ISSUE TITLE
Hydrogen bond not detected

### ISSUE THREAD

**Issue by cbouy** [chemosim-lab/ProLIF#28]
By default, ProLIF does not consider aromatic nitrogen as good HBond acceptors, so we've excluded them from the definition of hydrogen bonds.
However, if you want ProLIF to include those as well, it's very simple! Here is some code to do that:
 ```python
class HBAcceptor(plf.interactions.HBAcceptor):
    def __init__(self):
        super().__init__(acceptor="[#7,#8,F,-{1-};!+{1-}]")

class HBDonor(plf.interactions.HBDonor):
    def __init__(self):
        super().__init__(acceptor="[#7,#8,F,-{1-};!+{1-}]")

fp = plf.Fingerprint()
```
By default `plf.Fingerprint` includes Hbond interactions among others, and it will use the modified HBAcceptor and HBDonor classes.  
Make sure to use the same names for your interaction classes, otherwise you have to include them manually in the fingerprint with:
`fp = plf.Fingerprint(["CustomHBAcceptor", "CustomHBDonor", "HBAcceptor", "HBDonor"])`

More information on writing your own interaction classes are available [here](https://prolif.readthedocs.io/en/latest/notebooks/how-to.html#Writing-your-own-interaction)

**Comment by noorikhalifa** [comment]
It would be great if you can add this in the documentation so people don't miss out on this.
