### ISSUE TITLE
Segmentation fault if convert RDKit Mol objects to prolif.Molecule

### ISSUE THREAD

**Issue by DrrDom** [chemosim-lab/ProLIF#31]
The following code raises segmentation fault on the last line. LIgands were read successfully. Tested on prolif 0.3.4 and RDKIt 2021.03.5.
```
import prolif as plf
from rdkit import Chem
ligs = list(Chem.SDMolSupplier('1.sdf'))
plf.Molecule(ligs[0])
```
I know that I can use `plf.sdf_supplier` (I checked, it works), but I use prolif directly from a script to analyze molecules on the-the-fly and would like to avoid unnecessary saving data to the disk.

I attached an sdf (remove .txt extension)

[1.sdf.txt](https://github.com/chemosim-lab/ProLIF/files/7482363/1.sdf.txt)

**Comment by cbouy** [comment]
Hi @DrrDom

Here are a few steps you could try to fix the problem (you might not need all of them):

1. Keep hydrogens when reading the sdfile with `Chem.SDMolSupplier(..., removeHs=False)`
 
2. On a similar note, your molecules seem to only contain some but not all hydrogens. Add a `mol = Chem.AddHs(ligs[0], addCoords=True, addResidueInfo=True)` before passing the mol to plf.Molecule

3. Use `plf.Molecule.from_rdkit` to make sure every ligand atom belongs to a residue, which is required to produce the output fingerprint

Please tell me if it works for you

**Comment by DrrDom** [comment]
Options 1 and 2 did not help. Option 3 works.
Thank you!
