### ISSUE TITLE
ligand protein interactions for trajectory with united atoms

### ISSUE THREAD

**Issue by askusay** [chemosim-lab/ProLIF#33]
Thank you for creating this repository!

I am working with a united atom trajectory which causes issues at the the `fp.run` method:

```
lig = u.select_atoms("resname LIG")
prot = u.select_atoms("resnum 3-200") 
fp = plf.Fingerprint()
fp.run(u.trajectory[::10], lig, prot)
```

Which gives the assertion error:
```
No hydrogen atom could be found in the topology, but the converter requires all hydrogens to be explicit. You can use the parameter ''NoImplicit=False'' when using the converter to allow implicit hydrogens and disable inferring bond orders and charges. You can also use ''force=True'' to ignore this error.
```

I have confirmed that the `plf.Molecule.from_mda` method works with the `NoImplicit=False` and gives the correct topology when viewed in Jupyter notebook:

```
pmol = plf.Molecule.from_mda(prot, NoImplicit=False)
lmol = plf.Molecule.from_mda(lig, NoImplicit=False)
```

I hope I didn't missed something obvious! but how do I use the converted molecules with `fp.run`?, it seems to expect an MDAanalysis atom group does not seem to have kwargs during `plf.Fingerprint()` or `fp.run`

 Thanks in advance,

Ali

**Comment by askusay** [comment]
Hi Cedric, 

Thank you very much for the prompt reply, your script worked and by adding the flag `return_atoms=True` to `fp.generate` and `plf.to_dataframe`, I managed to display the `LigNetwork`. 

The `LigNetwork` only displayed hydrophobic and Hbond interactions, pi-cation, ionic and pi-stacking interactions were not detected, this is due to the `NoImplicit=False` flag. 

Here is an [image of the ligand](https://imgur.com/a/wKVcjgD), there is probably no simple way to add in the correct missing atoms for every trajectory frame or indicate to prolif which groups are actually ionic and aromatic. Let me know if you have some suggestions and feel free to close this ticket 

Thank you for your help!

**Comment by cbouy** [comment]
If you happen to have a file (PDB, MOL2 or others) with **all-atoms** of your ligand/protein complex for which the coordinates match with a frame (ideally the first) of your united-atoms trajectory, I think there might be a way.

Basically the idea is to make a mapping between atoms from the united-atoms (UA) to the all-atoms (AA) structures, and then for each frame you can use this mapping to copy bond orders and charges from AA to UA, which will then let you add the missing hydrogens with RDKit and use the resulting molecules in prolif.

I can help you with the code if you have an all-atom structure that matches a frame of your trajectory (typically the input file that you used to prepare the UA structure).

**Comment by askusay** [comment]
Hi Cedric, thank you very much for the offer to help
I have PDB files for the UA and AA ligand, which are matched by atom name
I am quite unfamiliar with RDKit, could you give me a clue as to how I can copy bond orders and charges from AA to UA?

**Comment by cbouy** [comment]
Do you also have it for the protein ?

**Comment by askusay** [comment]
The AA pdb files have OPLS naming while the UA files have gromos 54a7 naming. 
A few protein residue atoms and residue names would have to be changed in the AA files to make them 1:1
But now that I think about it, it might actually be possible to use [PDBFixer](https://github.com/openmm/pdbfixer), on individual simulation frames to add hydrogen atoms for the protein, what do you think?

**Comment by cbouy** [comment]
>The AA pdb files have OPLS naming while the UA files have gromos 54a7 naming.

That's typically why I'd rather rely on atom coordinates than atom naming to create the mapping.

>But now that I think about it, it might actually be possible to use PDBFixer, on individual simulation frames to add hydrogen atoms for the protein, what do you think?

I've never used it, but you could definitely give it a try for the protein

**Comment by askusay** [comment]
Hi Cedric,

Happy to report that I've now solved this issue using PyMOL, I did it by adding missing hydrogen atoms to all simulation frames.

### How to:
1) Load topology i.e. pdb file into PyMOL
2) Select the ligands `(lig sel)` and set the [`valence`](https://pymolwiki.org/index.php/Valence) of their bonds using the `valence guess, lig_sel` command. *(see notes for some tips on this)*
3) Load the simulation using [`load_traj`](https://pymolwiki.org/index.php/Load_traj)
4) Run the [`h_add`](https://pymolwiki.org/index.php/H_Add) *(see notes)*
5) Save the simulation preferably as a dcd file using [`save_trj`](https://github.com/speleo3/pymol-psico/blob/master/psico/exporting.py) or as individual pdb files - *much slower and larger files*. The `save_trj` function must be [installed from here](https://github.com/speleo3/pymol-psico)
6) Load simulation using MDAnalysis and run `uni.atoms.guess_bonds()` where `uni` is the universe object. More on this in #25
7) Now the analysis should work as intended

### Notes:
1) I suspect that the `valence` command may not work for complex ligands, in this case a combination of the [`valence`](https://pymolwiki.org/index.php/Valence) and [`bond`](https://pymolwiki.org/index.php/Bond) with the appropriate options may be needed 
2) Some elements types may need to be manually set in PyMOL, I.e. to set an atom to bromide: `alter atom_sel, element="BR"`. This can also be done in MDAnalysis by iterating over the atoms and setting their elements
3) The valence must be set correctly before running `h_add` otherwise hydrogens will be added incorrectly i.e. for aromatic systems 

Thanks for your help Cedric! Feel free to close the ticket or provide any comments on this.

**Comment by cbouy** [comment]
Hi Ali,

Good to know that you've managed to solve the issue!
Thanks for posting the procedure that you've used, I'm sure that it will be helpful to someone.

Take care,
Cédric
