### ISSUE TITLE
Savinf the fp object

### ISSUE THREAD

**Issue by ale94mleon** [chemosim-lab/ProLIF#40]
Hello, excelent work!
I am trying to save the fingerprint (becasue the calculation is expensive). I tried with:

```python
import pickle
with open('fp.pkl', 'wb') as file:
    pickle.dump(fp, file)
```
However, I got the error:

> [PicklingError: Can't pickle <function _Distance.detect at 0x7f77fa3725e0>: it's not the same object as prolif.interactions._Distance.detect]()

Any idea why this? Or even better, how to save the fp for future works?

**Comment by cbouy** [comment]
Hi @ale94mleon and thanks!

I'll have a look into exporting the fingerprint object as a pickle in the future. 

In the meantime, you can convert the fingerprint to a dataframe, and then export the dataframe to a pickle object :

```python
df = fp.to_dataframe()
df.to_pickle("dataframe.pkl")
```
Upon converting the fingerprint to a dataframe, you have several options available to include or exclude some info (namely `drop_empty` and `return_atoms`). Type `help(fp.to_dataframe)` to get more details on that.

So to be safe I would suggest saving both `fp.to_dataframe()` and `fp.to_dataframe(return_atoms=True)` just in case you need them later.
Both of these dataframes should contain everything you need for subsequent analysis!

Hope that helps,

Cédric
