### ISSUE TITLE
Can ProLIF generate FP based on a Prot PDB and a Lig PDB?

### ISSUE THREAD

**Issue by yipy0005** [chemosim-lab/ProLIF#41]
Hi, I understand that ProLIF reads a trajectory and generates the FP. But when I only have a prot.pdb and a lig.pdb, I tried generating the fp, while it can capture the residues near the ligand, all the interactions were not detected. So must I use a trajectory file to generate FP?

Thanks. :)

**Comment by cbouy** [comment]
Hi @yipy0005,

ProLIF should work with any kind of input (trajectories, docking poses and others) but it may need a bit of tweaking.
Here's an example script for 2 separate pdb files:

```python
prot = mda.Universe("prot.pdb")
lig = plf.Molecule.from_mda("lig.pdb")

prot_mol = plf.Molecule.from_mda(prot) 
lig_mol = plf.Molecule.from_mda(lig)
fp = plf.Fingerprint()
fp.run_from_iterable([lig_mol], prot_mol)
df = fp.to_dataframe()
```

Hope that helps,
Cédric

**Comment by cbouy** [comment]
I forgot to mention something important: both PDB files must have **all hydrogen atoms explicit**. Without this, ProLIF will not work correctly.

If you do not satisfy this requirement, you still have a workaround:
- for the protein, use protonation webservers/softwares and then read the resulting protonated pdb file
- for the ligand, you can use a SMILES string (which contains bond orders and formal charges), and merge it with your ligand PDB using rdkit's `AllChem.AssignBondOrdersFromTemplate` (more info [here](https://www.rdkit.org/docs/source/rdkit.Chem.AllChem.html#rdkit.Chem.AllChem.AssignBondOrdersFromTemplate) and then add hydrogens (still using rdkit) :

```python
# ligand
template = Chem.MolFromSmiles("CCO")
mol = Chem.MolFromPDBFile("lig.pdb")
mol = AssignBondOrdersFromTemplate(template, mol)
mol = Chem.AddHs(mol, addCoords=True, addResidueInfo=True)
lig_mol = plf.Molecule.from_rdkit(mol)

# compute fingerprint
# ... 
```
