### ISSUE TITLE
Filter backbone-backbone interactions and not backbone-side chain interactions

### ISSUE THREAD

**Issue by askusay** [chemosim-lab/ProLIF#42]
Hello again, 

For my protein-protein analysis, I would like to filter out backbone-backbone interactions alone, I have a hunch that I can use the numbers from `fp.to_dataframe(return_atoms=True)` to identify backbone atoms. However, I can't really figure out which atoms are meant to belong to the backbone and which ones belong to the side chain. [In the linked dataframe image](https://imgur.com/a/bkX32zf), atoms 3 and 9 correspond with the O and H backbone atoms for CYS200.A. It would seem that the N and O atoms are easy to identify since they are written first in the pdb file for all residues but H is residue dependent. 

Let me know what you think!

Cheers, 

Ali

**Comment by cbouy** [comment]
Hi again Ali,

There is a problem with this approach (but there is an alternative, no worries):

When ProLIF calculates an interaction for a pair of residues, if 2 groups of atoms (one for each residue) satisfy the requirements for that interaction type and residue pair, it saves it and goes to the next interaction type or residue pair.  
Now their might be more than 2 groups of atoms that satisfied this interaction's requirements, i.e. maybe the Hydrophobic interaction happens for both sidechain (SC) and backbone (BB) atoms, but because ProLIF first saw the one with the BB and stopped there, with your *post-hoc* method you might unknowingly filter out a SC-BB or SC-SC interaction tha prolif has skipped.

The alternative requires to rerun the analysis with the following code, which works this way:
- create the necessary `prolif.Molecule` objects from your proteins
- remove backbone atoms for protein n°1 but not protein n°2, then calculate the IFP to obtain the SC1-BB2 and SC1-SC2 interactions
- remove backbone atoms for protein n°2 but not protein n°1, then calculate the IFP to obtain the SC1-SC2 and BB1-SC2 interactions
- merge both IFPs, which won't contain any BB1-BB2 interactions

```python
import MDAnalysis as mda
import prolif as plf
from rdkit import Chem
from rdkit.Chem import AllChem
from tqdm.auto import tqdm
import pandas as pd

# load traj
u = mda.Universe(plf.datafiles.TOP, plf.datafiles.TRAJ)
# prepare selections
prot1 = u.select_atoms("resid 119:152")
prot2 = u.select_atoms("protein and not group prot1", prot1=prot1)

# function to remove backbone
backbone = Chem.MolFromSmarts("[C^2](=O)-[C;X4](-[H])-[N+0;D3]")
cterm_oxygen = Chem.MolFromSmarts("[O+0;X1;H1]")
lonely_h = Chem.MolFromSmarts("[H;+0;D0]")

def remove_backbone(mol):
    m = AllChem.DeleteSubstructs(mol, backbone)
    m = AllChem.DeleteSubstructs(m, cterm_oxygen)
    m = AllChem.DeleteSubstructs(m, lonely_h)
    return plf.Molecule(m)

# generate IFP
fp = plf.Fingerprint()
ifp1, ifp2 = [], []
for ts in tqdm(u.trajectory):
    p1 = plf.Molecule.from_mda(prot1)
    p2 = plf.Molecule.from_mda(prot2)
    # SC1-BB2 and SC1-SC2
    p1_no_bb = remove_backbone(p1)
    data1 = fp.generate(p1_no_bb, p2, return_atoms=True)
    data1["Frame"] = ts.frame
    ifp1.append(data1)
    # SC1-SC2 and BB1-SC2
    p2_no_bb = remove_backbone(p2)
    data2 = fp.generate(p1, p2_no_bb, return_atoms=True)
    data2["Frame"] = ts.frame
    ifp2.append(data2)

# get dataframes and merge them
df1 = plf.to_dataframe(ifp1, fp.interactions.keys())
df2 = plf.to_dataframe(ifp2, fp.interactions.keys())
df = (
    pd.concat([df1, df2], axis=1)
    .groupby(level=["ligand", "protein", "interaction"], axis=1)
    .sum()
    .astype(bool)
)
```

If you need the dataframe with atom indices, the code under the `# get dataframes` comment becomes a bit more complicated since the indices available when you do `plf.to_dataframe(ifp1, fp.interactions.keys(), return_atoms=True)` correspond to the backboneless version of the protein, but as always there's a workaround! Just tell me if you need it.

Cheers,
Cédric

**Comment by cbouy** [comment]
Actually I'll just post the code for dataframes with atom indices, in case anyone needs it in the future:

```python
def convert_backboneless_index(idx, residue, mol, mol_no_bb):
    if idx is None:
        return None
    no_bb_idx = mol_no_bb[residue].GetAtomWithIdx(idx).GetIntProp("_MDAnalysis_index")
    return next(a.GetIdx()
                for a in mol[residue].GetAtoms()
                if a.GetIntProp("_MDAnalysis_index") == no_bb_idx)

# get dataframes with "wrong" atom indices
dfa1 = plf.to_dataframe(ifp1, fp.interactions.keys(), return_atoms=True)
dfa2 = plf.to_dataframe(ifp2, fp.interactions.keys(), return_atoms=True)

# convert atom indices
def apply_conversion(s, position, mol, mol_no_bb):
    residue = s.name[position]
    if position == 0:
        return s.apply(lambda x: (convert_backboneless_index(x[0], residue, mol, mol_no_bb), x[1]))
    else:
        return s.apply(lambda x: (x[0], convert_backboneless_index(x[1], residue, mol, mol_no_bb)))
    
dfa1 = dfa1.apply(apply_conversion, position=0, mol=p1, mol_no_bb=p1_no_bb)
dfa2 = dfa2.apply(apply_conversion, position=1, mol=p2, mol_no_bb=p2_no_bb)
dfa = pd.concat([dfa1, dfa2], axis=1)
```
The resulting dataframe may contain 2 times the same interaction type for the same pair of residues (but different atoms). I'm not sure if the visualisation code snippets shown in the documentation would still work with that. If not, you can merge them with the following code:

```python
def merge(s):
    return (s
            .apply(lambda x: (-1, -1) if x == (None, None) else x)
            .sort_values(ascending=False)
            .apply(lambda x: (None, None) if x == (-1, -1) else x)
            .head(1))
    
dfa = (
    pd.concat([dfa1, dfa2], axis=1)
    .groupby(level=["ligand", "protein", "interaction"], axis=1)
    .agg(merge)
)
```

**Comment by askusay** [comment]
Hi Cédric,

Thanks for the explanation and the code. In my case, I am using the same protein selection for fingerprint, i.e.:
```
prot1 = u.select_atoms("resid 119:152")
sim.run(trj.trajectory[::10], prot1, prot1)
```
Does this mean that I need to iterate over each residue, and do two calculations:
residue with backbone - other residues without backbone?
residue without backbone - residue with backbone?

Or is there another method?

Cheers, 

Ali

**Comment by cbouy** [comment]
If prot1 == prot2 then you don't need to do it twice, once is sufficient, and the code becomes a bit simpler:

```python
import MDAnalysis as mda
import prolif as plf
from rdkit import Chem
from rdkit.Chem import AllChem
from tqdm.auto import tqdm
import pandas as pd

# load traj
u = mda.Universe(plf.datafiles.TOP, plf.datafiles.TRAJ)
# prepare selections
prot = u.select_atoms("resid 119:152")

# function to remove backbone
backbone = Chem.MolFromSmarts("[C^2](=O)-[C;X4](-[H])-[N+0;D3]")
cterm_oxygen = Chem.MolFromSmarts("[O+0;X1;H1]")
lonely_h = Chem.MolFromSmarts("[H;+0;D0]")

def remove_backbone(mol):
    m = AllChem.DeleteSubstructs(mol, backbone)
    m = AllChem.DeleteSubstructs(m, cterm_oxygen)
    m = AllChem.DeleteSubstructs(m, lonely_h)
    return plf.Molecule(m)

# generate IFP
fp = plf.Fingerprint()
ifp = []
for ts in tqdm(u.trajectory):
    p = plf.Molecule.from_mda(prot)
    p_no_bb = remove_backbone(p)
    # SC1-BB1 and SC1-SC1
    data = fp.generate(p_no_bb, p, return_atoms=True)
    data["Frame"] = ts.frame
    ifp.append(data)

# get dataframe
df = plf.to_dataframe(ifp, fp.interactions.keys())

# df with atom indices
def convert_backboneless_index(idx, residue, mol, mol_no_bb):
    if idx is None:
        return None
    no_bb_idx = mol_no_bb[residue].GetAtomWithIdx(idx).GetIntProp("_MDAnalysis_index")
    return next(a.GetIdx()
                for a in mol[residue].GetAtoms()
                if a.GetIntProp("_MDAnalysis_index") == no_bb_idx)

def apply_conversion(s, mol, mol_no_bb):
    residue = s.name[position]
    return s.apply(lambda x: (convert_backboneless_index(x[0], residue, mol, mol_no_bb), x[1]))

dfa = plf.to_dataframe(ifp, fp.interactions.keys(), return_atoms=True)
dfa = dfa.apply(apply_conversion, mol=p, mol_no_bb=p_no_bb)
```

**Comment by askusay** [comment]
Hi Cédric,

Thanks for this

Cheers
