### ISSUE TITLE
Parallelization

### ISSUE THREAD

**Issue by ale94mleon** [chemosim-lab/ProLIF#46]
This is not an issue, it is more a question/suggestion. Is it possible to parallelize the method `run` of the `class Fingerprint`? I was trying to look on the MDanalysis documentation and this is not so straightforward because how `MDAnalysis.core.universe.Universe.trajectory` is designed. But I also read about PMDanalysis. So, should not be possible to incorporate the parralelization to **ProLIF**? I think that this feature will really improve the package and the usability.

**Comment by ale94mleon** [comment]
Cool! This looks very nice. Thanks @cbouy !!

**Comment by noahharrison64** [comment]
Just to come back to this - It seems like the solution I posted above has it's issues. If I try to access map index property on a mol run through the multiprocessor (with Chem DefaultPickleProperties assigned to All), the map index is available but it doesn't correspond to the correct atomic numbering in the input file. If I do the same without the multiprocessing then the atomic numbering is correct.

**Comment by cbouy** [comment]
That doesn't sound right! Thanks for reporting it, I'll try to have a look soon
