### ISSUE TITLE
Water bridge interaction

### ISSUE THREAD

**Issue by ale94mleon** [chemosim-lab/ProLIF#47]
In some cases the water molecules have an important role in the binding. Could be added this kind of interaction to ProLIF?

**Comment by cbouy** [comment]
Hi @ale94mleon,

ProLIF is not really made to do 3-body interactions and I don't plan on implementing such interaction in the future.

The only way to do this would be to run the fingerprint analysis separately on `[ligand, water]`, then on `[water, protein]` selections with only `HBAcceptor` and `HBDonor`, and then somehow identify matching residue names in both dataframes:

```python
lig = u.select_atoms("resname LIG")
prot = u.select_atoms("protein")
water = u.select_atoms("resname WAT")

fp = plf.Fingerprint(["HBAcceptor", "HBDonor"])
dfLW = fp.run(u.trajectory, lig, water).to_dataframe().rename_axis(columns={"protein": "water"})
dfWP = fp.run(u.trajectory, water, prot).to_dataframe().rename_axis(columns={"ligand": "water"})

# identify columns where water residue names match
mask_lw = dfLW.columns.get_level_values("water").isin(dfWP.columns.get_level_values("water"))
mask_wp = dfWP.columns.get_level_values("water").isin(dfLW.columns.get_level_values("water"))
dfLW_match = dfLW.iloc[:, mask_lw]
dfWP_match = dfWP.iloc[:, mask_wp]

# combine both df
```

**Comment by ale94mleon** [comment]
Thanks!
