### ISSUE TITLE
Residue numbering 

### ISSUE THREAD

**Issue by noahharrison64** [chemosim-lab/ProLIF#59]
Hi Cédric,

I've been encountering an issue with residue numbering after running the fingerprint module. I'm not sure if this is something you've seen before, but when I run a protein (mol2 file) through the fingerprint a series of numbers are appended to the end of the normal residue numbering system.
For example, the correct residue numbering below would be ARG1086, as oppose to ARG108636. Each residue has it's correct number as the first 4 digits, then a set of digits appended. Another example is ASP1222172 should just be ASP1222. 
![image](https://user-images.githubusercontent.com/79198385/173539924-283d5800-efaa-4334-9f36-c419deb9b172.png)

Have you seen this issue before?[ I have attached the mol2 file if that helps debugging](https://drive.google.com/file/d/1xB_E33s1S9FCNj2pA9TZHyGmIgxsnHj4/view?usp=sharing), and a [plain text version of the file so you don't have to download.](https://drive.google.com/file/d/163bM-A1eHjugH7s_ZjEzZvc_pz1n-q43/view?usp=sharing)
I recall having the same issue when running with PDB files, although I will have to see if I can dig out an example of this. 

Many thanks,
Noah

**Comment by cbouy** [comment]
Hi Noah,

Can you check how MDAnalysis is reading those residues, more specifically residue names?

`u.atoms.residues.resnames`

It might be reading the combination of residue name and number as if it only contained the name, and then creates an additional numbering.

Best
Cédric

**Comment by noahharrison64** [comment]
Cédric, thanks for the rapid reply as always.

It looks like the issue arises when running
mol = prolif.Molecule.from_mda(u.atoms)
`
Since 
print(u.atoms.residues.resnames[50])
ASP1101

mol = prolif.Molecule.from_mda(u.atoms)
print([res for res in mol.residues][50])
ASP110151

` 
Best,
Noah

**Comment by noahharrison64** [comment]
Interestingly, if I don't use the print function on the prolif residue then it returns the ResidueID object which looks fine:
```
[res for res in mol.residues][50]
ResidueId(ASP1101, 51, None)
```

**Comment by cbouy** [comment]
The correct ResidueId should be `ResidueId(ASP, 1101, None)`

To fix this you'd have to iterate over u.residues.resnames, split the ASP and 1101 parts, and reassign u.residues.resnames and u.residues.resids

**Comment by noahharrison64** [comment]
Thanks Cédric I'll give that a go.
