### ISSUE TITLE
lignetwork with docked structures (pdbqt).

### ISSUE THREAD

**Issue by noorikhalifa** [chemosim-lab/ProLIF#60]
Hi, 

I was testing the lignetwork to generate images for the docked pose using the pdbqt files but while converting using pdbqt_to_mol function to give an input as an rdkit mol, I am getting the following error.

Thank you, looking forward for a solution or an advice. 
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/63507090/173805276-7ab22072-1454-41d6-90eb-ad1e2cb34d53.png)

**Comment by cbouy** [comment]
Hi @noorikhalifa,

You should be able to just use `lig_suppl[0]` (where `0` means you're asking for the first PDBQT file in the list that was used as input when you created your `lig_suppl`) to get a Molecule object.
Alternatively, you can use `lig_suppl.pdbqt_to_mol` but then the argument should be the **path to a PDBQT file**, *not* a folder containing the PDBQT files. i.e. something like `lig_suppl.pdbqt_to_mol("/home/user/projects/ABC/docking/results/pose_1.pdbqt")`

Hope this is clear,

Cédric
