### ISSUE TITLE
Interaction descriptions

### ISSUE THREAD

**Issue by andresilvapimentel** [chemosim-lab/ProLIF#62]
How can I change the fonts for interaction descriptions to visualize better the LigNetwork diagram?
Is it possible to increase the font of residues?

**Comment by andresilvapimentel** [comment]
Is it possible to increase the graphic resolution of the LigNetwork diagram?

**Comment by cbouy** [comment]
You can try to modify both `height="500px"` and `fontsize=20` when calling `net.display()`:
```python
net.display(height="1200px", fontsize=32)
```
Unfortunately fontsize controls both heteroatom and residue label font size, you cannot distinguish the two.
