### ISSUE TITLE
LigNetwork does not show interactions

### ISSUE THREAD

**Issue by andresilvapimentel** [chemosim-lab/ProLIF#64]
LigNetwork does not show interactions, but there is a warning:

/usr/local/lib/python3.7/dist-packages/MDAnalysis/converters/RDKit.py:422: UserWarning: No `bonds` attribute in this AtomGroup. Guessing bonds based on atoms coordinates
  "No `bonds` attribute in this AtomGroup. Guessing bonds based "

I am not sure if this is related to the absence of conectivity in the pdb file. Do you have any idea?

**Comment by cbouy** [comment]
Closing this issue, feel free to reopen if there's still a problem.
