### ISSUE TITLE
Prolif is not working independently of the Operating System on some PDB files.

### ISSUE THREAD

**Issue by Bio-Otto** [chemosim-lab/ProLIF#67]
Hi @cbouy,
 
When I try to load my protein file (I already attached it below) to **Prolif** using **MDAnalysis**, it's killing the kernel on Jupyter Notebook. I tried both from conda-forge channel and by installing with pip. I've also tried it for Ubuntu and Windows operating systems. But the result did not change. I have attached the file below to see if this is a bug or not.

Congratulations on this beautiful package. Also, thank you for your time.

```python
import prolif as plf
import MDAnalysis as mda

receptor= 'receptor.pdb'

# load protein
prot = mda.Universe(receptor)
prot = plf.Molecule.from_mda(prot)
```

[receptor.pdb.txt](https://github.com/chemosim-lab/ProLIF/files/9162519/receptor.pdb.txt)

**Comment by cbouy** [comment]
Hi,

You need all hydrogen atoms to be explicit in your protein file if you are using the interface with MDAnalysis, and your file only has the polar ones.

I suggest you try directly using RDKit for the input:
```python
from rdkit import Chem

prot = Chem.MolFromPDBFile("receptor.pdb")
prot = plf.Molecule.from_rdkit(prot )
```

If you have a ligand in a separate file, you'll either need a PDB with all hydrogens and use the MDAnalysis interface just for the ligand, or if you have a MOL2 or SDF, you can either use the [builtin suppliers](https://prolif.readthedocs.io/en/latest/source/modules/input.html#prolif.molecule.mol2_supplier) which can handle multiple ligands:
```python
lig_suppl = plf.mol2_supplier("ligands.mol2")
fp = plf.Fingerprint()
fp.run_from_iterable(lig_suppl, prot)
df = fp.to_dataframe()
```

or just use RDKit as above:
```python
lig = Chem.MolFromPDBFile("lig.mol2")
lig = plf.Molecule.from_rdkit(lig)
fp = plf.Fingerprint()
fp.run_from_iterable([lig], prot)
df = fp.to_dataframe()
```

**Comment by cbouy** [comment]
Closing this issue, feel free to reopen if there's still a problem.
