### ISSUE TITLE
How to list interaction lengths with Prolif?

### ISSUE THREAD

**Issue by Bio-Otto** [chemosim-lab/ProLIF#71]
I've read Prolif's manual but haven't seen a function that lists the distances of the interactions found. I just saw that it lists "True-False" and atomic indices. Also, how can I do this in the most correct way? Thank you in advance for your help.

**Comment by noahharrison64** [comment]
Haven't figured out how to extract information like bond angle or distances from the prolif/interactions/Interactions class but you can pull this information from the fingerprint dataframe.

```
from rdkit import Geometry
df = fp.to_dataframe(return_atoms = True)
distances = []
for i, row in df.T.iterrows():
    lresid, presid, interaction = i
    lindex, pindex = row[0]
    lres = lmol[lresid]
    pres = pmol[presid]
    # get coordinates for both points of the interaction
    if interaction in ["PiStacking", "EdgeToFace", "FaceToFace", "PiCation"]:
        p1 = get_ring_centroid(lres, lindex)
    else:
        p1 = lres.GetConformer().GetAtomPosition(lindex)
    if interaction in ["PiStacking", "EdgeToFace", "FaceToFace", "CationPi"]:
        p2 = get_ring_centroid(pres, pindex)
    else:
        p2 = pres.GetConformer().GetAtomPosition(pindex)

     lres_xyz = Geometry.Point3D(*p1)
     pres_xyz = Geometry.Point3D(*p2)
     distances.append(lres_xyz.Distance(pres_xyz))
      
```

Haven't tested this but this should provide the blueprint of the tools you need.

**Comment by cbouy** [comment]
There isn't currently a way to directly obtain that from the fingeprint calculation but I'll definitely consider adding some interactions metadata in the updates to come!

@noahharrison64 's script shows how to measure the distances based on the atomic indices, some of the functions used there come from the [Visualisation tutorial](https://prolif.readthedocs.io/en/latest/notebooks/visualisation.html) so make sure to have a look there.

Thanks @noahharrison64 for the help!
