### ISSUE TITLE
Plot prot-prot interactions as prot-lig fingerprint

### ISSUE THREAD

**Issue by mamarambio1** [chemosim-lab/ProLIF#78]
Hi!
I am working with membrane domains in a protein and managed to identify interactions between residues in different domains thanks to the notebooks you have shared.
However, I would like to be able to obtain a type of graph similar to the one obtained when identifying the fingerprint between the protein and the ligand, in Jupyter is this possible?

Thanks!

**Comment by cbouy** [comment]
Hi @mamarambio1,

There's no direct way of plotting PPI with the LigNetwork, but there is a workaround in issue #58. 
Please check if the code snippet I shared there solves your problem. 

You'll have to rerun the analysis but hopefully that's not too much trouble. 

Best,
Cédric

**Comment by mamarambio1** [comment]
Hi @cbouy !

Thanks for the comment, but I think my question is directed another way.
I am working with a trajectory and I want to identify the type of interaction between the residues of two transmembrane domains.
I did the previous analysis and then I used this command:

# reorganize data
data = df.reset_index()
data = pd.melt(data, id_vars=["Frame"], var_name=["residue","interaction"])
data = data[data["value"] != False]
data.reset_index(inplace=True, drop=True)

# plot
sns.set_theme(font_scale=.8, style="white", context="talk")
g = sns.catplot(
    data=data, x="interaction", y="Frame", hue="interaction", col="residue",
    hue_order=["SER173","LYS174","ILE175","SER176","GLY177","LEU179","THR180",
               "THR183","SER184","ILE187","PRO188","ILE191"],
    height=3.5, aspect=0.2, jitter=0, sharex=False, marker="_", s=5, linewidth=3.5,
)
g.set_titles("{col_name}")
g.set(xticks=[], ylim=(-.5, data.Frame.max()+1))
g.set_xticklabels([])
g.set_xlabels("")
g.fig.subplots_adjust(wspace=0)
g.add_legend()
g.despine(bottom=True)
for ax in g.axes.flat:
    ax.invert_yaxis()
    ax.set_title(ax.get_title(), pad=10, rotation=90, ha="center", va="baseline")


<img width="1053" alt="Captura de Pantalla 2022-08-10 a la(s) 15 16 57" src="https://user-images.githubusercontent.com/84489348/184001583-f008d9f9-ae6d-48bf-9a2d-098baa50e9b5.png">

But it does not show the type of interaction between amino acids, is it possible to add something to the command line that can indicate the type of interaction?

**Comment by cbouy** [comment]
Ah yes I get it now.

Here's how to get the same plot for PPI:
```python
# reorganize data
data = df.reset_index()
data = pd.melt(data, id_vars=["Frame"])
data = data[data["value"] != False]
# sort residues
data["sort_key_ligand"] = data["ligand"].apply(plf.ResidueId.from_string)
data["sort_key_protein"] = data["protein"].apply(plf.ResidueId.from_string)
data.sort_values(["Frame", "sort_key_ligand", "sort_key_protein"], ascending=True, inplace=True)
# cleanup
data.drop(columns=["sort_key_ligand", "sort_key_protein"], inplace=True)
data.reset_index(inplace=True, drop=True)
# add column for labels
data["PPI"] = data.apply(lambda x: f"{x.ligand} {x.protein}", axis=1)


# plot
import warnings
warnings.filterwarnings("ignore", "You passed a edgecolor")

sns.set_theme(font_scale=.8, style="white", context="talk")
g = sns.catplot(
    data=data, x="interaction", y="Frame", hue="interaction", col="PPI",
    hue_order=["Hydrophobic", "HBDonor", "HBAcceptor", "PiStacking", "CationPi", "Cationic"],
    height=3, aspect=0.2, jitter=0, sharex=False, marker="_", s=8, linewidth=3.5,
)
g.set_titles("{col_name}")
g.set(xticks=[], ylim=(-.5, data.Frame.max()+1))
g.set_xticklabels([])
g.set_xlabels("")
g.fig.subplots_adjust(wspace=0)
g.add_legend()
g.despine(bottom=True)
for ax in g.axes.flat:
    ax.invert_yaxis()
    ax.set_title(ax.get_title(), pad=10, rotation=90, ha="left", va="baseline", rotation_mode="anchor")
```

**Comment by mamarambio1** [comment]
Hi @cbouy !
Thank you very much for the  help!
Regards
