### ISSUE TITLE
AttributeError: module 'prolif' has no attribute 'datafiles'

### ISSUE THREAD

**Issue by MarcAmil30** [chemosim-lab/ProLIF#79]
Hello 

When trying to go through the documentation to get familiarized with ProLIF, I followed the code (shown below) in the Quickstart section:
```
import MDAnalysis as mda
import prolif as plf
# load trajectory
u = mda.Universe(plf.datafiles.TOP, plf.datafiles.TRAJ)
# create selections for the ligand and protein
lig = u.atoms.select_atoms("resname LIG")
prot = u.atoms.select_atoms("protein")
lig, prot
```

However, I get this error ```AttributeError: module 'prolif' has no attribute 'datafiles'```. I want to ask how to prevent this. I have tried both using jupyter notebook and without jupyter notebook. 

Thanks

**Comment by cbouy** [comment]
Which version of Python and ProLIF is this?
Looks like you have an old and deprecated version installed.

**Comment by cbouy** [comment]
Closing this issue since no answer, feel free to reopen.
