### ISSUE TITLE
How to analysis the trajectory from MD simulation

### ISSUE THREAD

**Issue by tanshy17** [chemosim-lab/ProLIF#81]
Hello all !
I have a binpos trajectory file (eq5ns-nowater.binpos) and a topology file (gs_com.prmtop). It come back the error:
TypeError: Cannot find an appropriate coordinate reader for file 'eq5ns-nowater.binpos'.
Unknown coordinate trajectory format 'BINPOS' for 'eq5ns-nowater.binpos'. The FORMATs
dict_keys(['CHAIN', 'CHEMFILES', 'CRD', 'DCD', 'CONFIG', 'HISTORY', 'DMS', 'GMS', 'GRO', 'INPCRD', 'RESTRT', 'LAMMPS', 'DATA', 'LAMMPSDUMP', 'MOL2', 'PDB', 'ENT', 'XPDB', 'PDBQT', 'PQR', 'TRJ', 'MDCRD', 'CRDBOX', 'NCDF', 'NC', 'TRR', 'H5MD', 'TRZ', 'XTC', 'XYZ', 'TXYZ', 'ARC', 'MEMORY', 'MMTF', 'GSD', 'COOR', 'NAMDBIN', 'IN', 'FHIAIMS', 'PARMED', 'RDKIT', 'OPENMMSIMULATION', 'OPENMMAPP'])
are implemented in MDAnalysis.

Then I use the cpptraj in Amber to convert binpos to crd:
trajin eq5ns-nowater.binpos
trajout eq5ns-nowater.crd crd

 It feed back the error like that:
**Preparation step
/home/tim/anaconda3/envs/prolif/lib/python3.10/site-packages/MDAnalysis/coordinates/CRD.py:86: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  self.ts = self._Timestep.from_coordinates(np.array(coords_list),
ValueError: could not broadcast input array from shape (627500,) into shape (627500,3)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tim/tanshy/pingan-selectivity/docking/DNL201-AF-GS/ProLIF.py", line 25, in <module>
    u = mda.Universe(TOPOLOGY, TRAJECTORY)
  File "/home/tim/anaconda3/envs/prolif/lib/python3.10/site-packages/MDAnalysis/core/universe.py", line 365, in __init__
    self.load_new(coordinates, format=format, in_memory=in_memory,
  File "/home/tim/anaconda3/envs/prolif/lib/python3.10/site-packages/MDAnalysis/core/universe.py", line 565, in load_new
    self.trajectory = reader(filename, format=format, **kwargs)
  File "/home/tim/anaconda3/envs/prolif/lib/python3.10/site-packages/MDAnalysis/lib/util.py", line 2495, in wrapper
    return func(self, *args, **kwargs)
  File "/home/tim/anaconda3/envs/prolif/lib/python3.10/site-packages/MDAnalysis/coordinates/base.py", line 1553, in __init__
    self._read_first_frame()
  File "/home/tim/anaconda3/envs/prolif/lib/python3.10/site-packages/MDAnalysis/coordinates/CRD.py", line 86, in _read_first_frame
    self.ts = self._Timestep.from_coordinates(np.array(coords_list),
SystemError: <built-in method from_coordinates of type object at 0x153ce3985ec0> returned a result with an exception set**

I am new to python scripts. Could some one help me and fix it?
Thanks in advance !

below are me input :

#!/usr/bin/env python
from pathlib import Path
import MDAnalysis as mda
import numpy as np
import prolif as plf

# PARAMETERS #

OUTPUT_FOLDER = "."
TOPOLOGY = "gs_com.prmtop"
TRAJECTORY = "eq5ns-nowater.crd"
LIGAND_SELECTION = "resname DNL"  # the residue name for your ligand
                                  # you can also use "resid 123" if you prefer using residue numbers
PROTEIN_SELECTION = "protein"  # "protein" automatically selects the protein for you
# if unsure, use None for the following parameters, otherwise use an integer
START = 1  # start the analysis at this frame of your trajectory
STOP = 500  # stop the analysis at this frame
STEP = 1  # use one frame every STEP frames for the analysis

**Comment by tanshy17** [comment]
solved it when set the format:
# load MD simulation
u = mda.Universe(TOPOLOGY, TRAJECTORY, format="MDCRD")

**Comment by cbouy** [comment]
Hi @b-lillo , yes you can read Amber trajectories with MDAnalysis as explained in [their documentation](https://docs.mdanalysis.org/stable/documentation_pages/coordinates/TRJ.html#ascii-traj-trajectories). You can get a list of all the supported coordinates formats [here](https://docs.mdanalysis.org/stable/documentation_pages/coordinates/init.html#supported-coordinate-formats)
