### ISSUE TITLE
Problem when loading two trajectory files

### ISSUE THREAD

**Issue by ayyildizm** [chemosim-lab/ProLIF#82]
Hi, 

When i have one psf and one dcd file everything works fine, but with two dcd files the following error occurs:

`fp.run(u.trajectory[::2000], lig, prot)`
`df = fp.to_dataframe()`

`MDAnalysis.exceptions.NoDataError: This Universe has no coordinates`

**Comment by cbouy** [comment]
Hi @ayyildizm,

Could you provide the code snippet that you used to prepare the MDAnalysis Universe object? To specify the topology alongside two trajectory files, it should look something like this:
```python
u = mda.Universe("topology.psf", "traj1.dcd", "traj2.dcd")
```
