### ISSUE TITLE
Segmentation Fault ( Core Dumped ) in Molecule

### ISSUE THREAD

**Issue by akhilmedvolt** [chemosim-lab/ProLIF#85]
### Actual Issue
While trying to run `prot_mol = plf.Molecule.from_mda(prot)` **in a loop**, after certain iterations the **core is dumped**.

Here `prot = mda.Universe("proth.pdb")` and proth is created using `os.system("obabel prot.pdb -opdb -O proth.pdb -h")`. 

![ksnip_20221005-211822](https://user-images.githubusercontent.com/96740171/194118556-3122a001-5e0d-46ab-a3d6-ecc4a97112e5.png)

![ksnip_20221005-211810](https://user-images.githubusercontent.com/96740171/194118688-84af6ecd-f312-4238-be05-4f0660f42b4c.png)

**Comment by cbouy** [comment]
Hi @akhilmedvolt,

I think `openbabel` is having some trouble with your input PDB file, have you taken a look at the output `proth.pdb` file to see if it was generated correctly?

Also it's not a tool I'd personally use to protonate a protein structure to be honest, I'd suggest looking into something like `pypka` to generate the PDB with explicit hydrogens.

Best,
Cédric
