### ISSUE TITLE
Error when overwriting new interactions

### ISSUE THREAD

**Issue by i2nico** [chemosim-lab/ProLIF#86]
Hello, 

I followed the instructions within the section "_How-to_" and tried to change some interaction parameters, however, I received an _AttributeError_. In particular, this one:
**AttributeError: Can't get attribute 'Hydrophobic' on <module '__main__' (built-in)>**

As far as I understood this problem is related to: [Multiprocessing example giving AttributeError](https://stackoverflow.com/questions/41385708/multiprocessing-example-giving-attributeerror)

Indeed, if I create a module file and import the modified interaction classes it works. Another workaround which worked for me is to limit the amount of processes:

fp.run(universe.trajectory, lig, prot, **n_jobs=1**)

_Edit_: Might be possible that this error message is not visible in Jupyter Notebooks. In my case the error message was printed to the console.

Best wishes

**Comment by cbouy** [comment]
Hi @i2nico and thanks for reporting the issue and sharing a workaround!

Unfortunately I don't think there's an easy fix for this, apart from using a different multiprocessing library.
In the future I have plans to make customizing interactions a bit easier (through a YAML file or a dictionary), so I might try to implement this feature in such a way that it solves the issue you've described. But I can't give any timeline or guarantee for now.

Best,
Cédric
