### ISSUE TITLE
Empty dataframe output when generating interaction fingerprints

### ISSUE THREAD

**Issue by shinoxide** [chemosim-lab/ProLIF#87]
Thank you for your efforts. Prolif is quite easy to install.
Please the issue I have is that I keep getting empty dataframe output when I generate the fingerprints and read into pandas dataframe. My protein and ligands are okay, I confirmed interactions elsewhere. Please kindly help me out. See image please, thank you

![prolif_issue_095335](https://user-images.githubusercontent.com/80653989/197417941-217956de-def7-48e8-8dcc-8fbfdb2b1f9a.jpg)

**Comment by cbouy** [comment]
Hi @shinoxide ,

Does your protein PDB file have **explicit hydrogens on all atoms**? It's a requirement for ProLIF to work correctly. If not, you can use webservers like [PypKa](https://pypka.org/run-pypka) or PropKa (also available as command line tools) for this matter.

Another possible explanation would be that your protein PDB file has `CONECT` records for some of the bonds but not all, in which case you might want to load the PDB file with:
```python
prot = mda.Universe("myprot2.pdb", guess_bonds=True)
```

Tell me if this works.

Best,
Cédric

**Comment by shinoxide** [comment]
> 

Hi Cédric,

This is great! It worked! The "guess_bonds=True" worked for me. See picture. Thank you very much 😊 I'm grateful.
![prolif_solution_011410](https://user-images.githubusercontent.com/80653989/197523670-4e4aef71-c912-4049-b41b-2e26d9686a2b.jpg)

Adeshina

**Comment by shinoxide** [comment]
> Hi @shinoxide ,
> 
> Does your protein PDB file have **explicit hydrogens on all atoms**? It's a requirement for ProLIF to work correctly. If not, you can use webservers like [PypKa](https://pypka.org/run-pypka) or PropKa (also available as command line tools) for this matter.
> 
> Another possible explanation would be that your protein PDB file has `CONECT` records for some of the bonds but not all, in which case you might want to load the PDB file with:
> 
> ```python
> prot = mda.Universe("myprot2.pdb", guess_bonds=True)
> ```
> 
> Tell me if this works.
> 
> Best, Cédric

Hi Cédric

Thanks again for your response. I have 2 questions please.
1. Can I very much rely on the accuracy of `guess_bonds`?
2. Do you know tools I can use to capture `CONET` records for all bonds?
Thank you.

**Comment by cbouy** [comment]
> 1. Can I very much rely on the accuracy of `guess_bonds`?

MDAnalysis uses the same algorithm as VMD and many other tools for guessing bonds based on 3D coordinates and elements. so although it's not going to be completely failure-proof, I'd say it's pretty safe.
Also when you run `plf.Molecule.from_mda(prot)` it actually converts the full protein into an RDKit molecule, and RDKit will complain if it sees atoms with incorrect valences, so if there's a problem during bond guessing it will very likely result in an error on the RDKit side and you will know immediatly.

> 2. Do you know tools I can use to capture `CONECT` records for all bonds?

I'm not sure I understand the question, do you mean extracting all the lines that start with `CONECT` in your PDB file?
If so, on a Linux/Mac shell, the command `grep 'CONECT ' myprot2.pdb` should do the trick.

**Comment by shinoxide** [comment]
> > 1. Can I very much rely on the accuracy of `guess_bonds`?
> 
> MDAnalysis uses the same algorithm as VMD and many other tools for guessing bonds based on 3D coordinates and elements. so although it's not going to be completely failure-proof, I'd say it's pretty safe. Also when you run `plf.Molecule.from_mda(prot)` it actually converts the full protein into an RDKit molecule, and RDKit will complain if it sees atoms with incorrect valences, so if there's a problem during bond guessing it will very likely result in an error on the RDKit side and you will know immediatly.
> 
> > 2. Do you know tools I can use to capture `CONECT` records for all bonds?
> 
> I'm not sure I understand the question, do you mean extracting all the lines that start with `CONECT` in your PDB file? If so, on a Linux/Mac shell, the command `grep 'CONECT ' myprot2.pdb` should do the trick.

Thank you very much for your response.
For my second question... You said earlier that it is possible that my protein PDB file doesn't have `CONECT` records for all bonds and indeed I have only two lines starting with 'CONECT' in the file. So I thought there might be ways to generate complete `CONECT` records.

**Comment by cbouy** [comment]
MDAnalysis and RDKit can both read and write PDB files and have that functionality, VMD and probably PyMol or Avogadro also have that.

**Comment by shinoxide** [comment]
Thank you very much for your support.
